prompt --application/pages/page_00093
begin
--   Manifest
--     PAGE: 00093
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>666903967469575309
,p_default_application_id=>10021010
,p_default_id_offset=>759714394172364641
,p_default_owner=>'SUN_21010_DEV'
);
wwv_flow_imp_page.create_page(
 p_id=>93
,p_tab_set=>'TS1'
,p_name=>'Patient Diary Details'
,p_step_title=>'Patient Diary Details'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(4072823132821996210)
,p_process_sequence=>10
,p_process_point=>'BEFORE_HEADER'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'Create Schedule and Redirect'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'V_SCHEDULE_ID EDC_PATIENT_SCHEDULE_PARAMS.SCHEDULE_ID%TYPE;',
'V_TMP NUMBER;',
'v_patient_diary number;',
'V_CRF_ID NUMBER;',
'V_STUDY_SITE_ID NUMBER;',
'V_PAGE_NO NUMBER;',
'V_LAST_SCHEDULE_ID NUMBER;',
'V_LAST_SCHEDULE_TITLE VARCHAR2(100);',
'V_DURATION NUMBER;',
'V_LAST_SCHEDULE_DT VARCHAR(20);',
'V_LAST_SCHEDULE_TM VARCHAR2(20);',
'V_LAST_DIARY_ID NUMBER;',
'V_PK_ID NUMBER;',
'V_PATIENT_DIARY_ID NUMBER;',
'V_CNT NUMBER;',
'V_CNT1 NUMBER;',
'V_CNT2 NUMBER;',
'V_PK_ID1 NUMBER := 1;',
'V_PATIENT_DIARY_ID1 NUMBER;',
'V_DIARY_TYPE VARCHAR2(50);',
'v_audit_id number;',
'V_SCHEMA_NAME VARCHAR2(50);',
'',
'begin',
'',
'    SELECT DISTINCT OWNER INTO V_SCHEMA_NAME FROM ALL_TABLES WHERE OWNER LIKE ''%APPILI_COVID%'';',
'    ',
'    SELECT STUDY_SITE_ID, EPRO_DIARY_TYPE INTO V_STUDY_SITE_ID, V_DIARY_TYPE',
'    FROM EDC_PATIENT_PROFILE',
'    WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID;',
'',
'    select SCHEDULE_ID        --next schedule id',
'    INTO V_SCHEDULE_ID',
'    from EDC_PATIENT_SCHEDULE_PARAMS',
'    WHERE SCHEDULE_NAME = :APP_EDC_SCHEDULE_NAME',
'    AND STUDY_ID = :APP_EDC_STUDY_ID;',
' ',
'    select count(*) INTO V_TMP ',
'    from edc_patient_diary',
'    where UPPER(schedule_title)=UPPER(:APP_EDC_SCHEDULE_NAME) ',
'    and patient_profile_id=:APP_PATIENT_PROFILE_ID',
'    and study_id = :APP_EDC_STUDY_ID;',
'    ',
'    /*SELECT PAGE_NO INTO V_PAGE_NO     --FIND THE FIRST PAGE OF THE SCHEDULE',
'    FROM EDC_PATIENT_DIARY_PAGES',
'    WHERE APP_TYPE = ''WEB''',
'    AND UPPER(SCHEDULE_NAME) = UPPER(:APP_EDC_SCHEDULE_NAME)',
'    AND SEQ_NO = (SELECT MIN(SEQ_NO) FROM EDC_PATIENT_DIARY_PAGES',
'                  WHERE APP_TYPE = ''WEB''',
'                  AND UPPER(SCHEDULE_NAME) = UPPER(:APP_EDC_SCHEDULE_NAME));*/',
'    ',
'    IF V_TMP=0 THEN',
'         ',
'         SELECT SCHEDULE_ID, SCHEDULE_TITLE, TO_CHAR(SCHEDULE_DT,''DD-MM-YY''), TO_CHAR(SCHEDULE_TM,''HH24:MI'')',
'         INTO V_LAST_SCHEDULE_ID, V_LAST_SCHEDULE_TITLE, V_LAST_SCHEDULE_DT, V_LAST_SCHEDULE_TM',
'         FROM EDC_PATIENT_DIARY',
'         WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID',
'         AND PATIENT_DIARY_ID = (SELECT MAX(PATIENT_DIARY_ID) FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID);',
'        ',
'         SELECT DURATION INTO V_DURATION',
'         FROM EDC_PATIENT_SCHEDULE_PARAMS',
'         WHERE SCHEDULE_ID = V_SCHEDULE_ID;',
'    ',
'         /*INSERT INTO EDC_PATIENT_DIARY(PATIENT_PROFILE_ID, SCHEDULE_TITLE, SCHEDULE_STATUS, SCHEDULE_ID, STUDY_ID)',
'         VALUES(:APP_PATIENT_PROFILE_ID, :APP_EDC_SCHEDULE_NAME, 2,V_SCHEDULE_ID, :APP_EDC_STUDY_ID );',
'         COMMIT;*/',
'         ',
'         INSERT INTO EDC_PATIENT_DIARY(PATIENT_PROFILE_ID, SCHEDULE_TITLE, SCHEDULE_STATUS, SCHEDULE_ID, STUDY_ID, SECTION_STATUS, IS_SKIP, SCHEDULE_DT, SCHEDULE_TM, DIARY_TYPE,MANCRTD_YN)',
'         VALUES(:APP_PATIENT_PROFILE_ID, :APP_EDC_SCHEDULE_NAME, 2, V_SCHEDULE_ID, 661, 2, ''No'',',
'         TO_DATE(to_char(TO_DATE((V_LAST_SCHEDULE_DT||'' ''||V_LAST_SCHEDULE_TM),''DD-MM-YY HH24:MI'')+V_DURATION/24,''DD-MM-YY HH24:MI''),''DD-MM-YY HH24:MI''),',
'         TO_DATE(to_char(TO_DATE((V_LAST_SCHEDULE_DT||'' ''||V_LAST_SCHEDULE_TM),''DD-MM-YY HH24:MI'')+V_DURATION/24,''DD-MM-YY HH24:MI''),''DD-MM-YY HH24:MI''), V_DIARY_TYPE,''Yes'');',
'         ',
'         COMMIT;',
'        ',
'         SELECT PATIENT_DIARY_ID INTO V_PATIENT_DIARY_ID1',
'         FROM EDC_PATIENT_DIARY',
'         WHERE UPPER(SCHEDULE_TITLE) = UPPER(:APP_EDC_SCHEDULE_NAME)',
'         AND PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID',
'         AND STUDY_ID = :APP_EDC_STUDY_ID;',
'         ',
'         :APP_EDC_PATIENT_DIARY_ID := V_PATIENT_DIARY_ID1;',
'         ',
'         select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'      ',
'         insert into AUDIT_TRAIL(audit_log_id,TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PAGE_NO,COLUMN_NAME,',
'         OLD_VALUE,NEW_VALUE,ACTION,USERNAME,TABLE_PK_VALUE, PATIENT_DIARY_ID) ',
'         values(v_audit_id,''EDC_PATIENT_DIARY'',661,V_STUDY_SITE_ID ,:APP_PATIENT_PROFILE_ID,999,''SCHEDULE_DT'','''',',
'         to_char(TO_DATE((V_LAST_SCHEDULE_DT||'' ''||V_LAST_SCHEDULE_TM),''DD-MM-YY HH24:MI'')+V_DURATION/24,''DD-MM-YY HH24:MI''),',
'         ''INSERT'',UPPER(V_SCHEMA_NAME),V_PATIENT_DIARY_ID1, V_PATIENT_DIARY_ID1);',
'        ',
'         select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'        ',
'         insert into AUDIT_TRAIL(audit_log_id,TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PAGE_NO,COLUMN_NAME,',
'         OLD_VALUE,NEW_VALUE,ACTION,USERNAME,TABLE_PK_VALUE, PATIENT_DIARY_ID) ',
'         values(v_audit_id,''EDC_PATIENT_DIARY'',661,V_STUDY_SITE_ID ,:APP_PATIENT_PROFILE_ID,999,''SCHEDULE_TM'','''',',
'         to_char(TO_DATE((V_LAST_SCHEDULE_DT||'' ''||V_LAST_SCHEDULE_TM),''DD-MM-YY HH24:MI'')+V_DURATION/24,''DD-MM-YY HH24:MI''),',
'         ''INSERT'',UPPER(V_SCHEMA_NAME),V_PATIENT_DIARY_ID1, V_PATIENT_DIARY_ID1);',
'         ',
'         /*SELECT MIN(CRF_ID) INTO V_CRF_ID',
'         FROM EDC_PATIENT_DIARY_PAGES',
'         WHERE SCHEDULE_ID = V_SCHEDULE_ID',
'         AND STUDY_ID = :APP_EDC_STUDY_ID;*/',
'         ',
'         IF UPPER(:APP_EDC_SCHEDULE_NAME) LIKE ''%MORNING%'' OR UPPER(:APP_EDC_SCHEDULE_NAME) = ''DAY 14'' OR UPPER(:APP_EDC_SCHEDULE_NAME) = ''DAY 21'' THEN',
'        ',
'             IF UPPER(:APP_EDC_SCHEDULE_NAME) LIKE ''%MORNING%'' THEN',
'                 SELECT MAX(PATIENT_DIARY_ID) INTO V_LAST_DIARY_ID',
'                 FROM EDC_PATIENT_DIARY',
'                 WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID',
'                 AND UPPER(SCHEDULE_TITLE) LIKE ''%MORNING%''',
'                 AND PATIENT_DIARY_ID != V_PATIENT_DIARY_ID1;',
'             ELSIF UPPER(:APP_EDC_SCHEDULE_NAME) = ''DAY 14'' THEN',
'                 SELECT PATIENT_DIARY_ID INTO V_LAST_DIARY_ID',
'                 FROM EDC_PATIENT_DIARY',
'                 WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID',
'                 AND UPPER(SCHEDULE_TITLE) = ''DAY 10 MORNING'';',
'             ELSIF UPPER(:APP_EDC_SCHEDULE_NAME) = ''DAY 21'' THEN',
'                 SELECT PATIENT_DIARY_ID INTO V_LAST_DIARY_ID',
'                 FROM EDC_PATIENT_DIARY',
'                 WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID',
'                 AND UPPER(SCHEDULE_TITLE) = ''DAY 14'';',
'             END IF;',
'        ',
'             --FOR CARRYING FORWARD SYMPTOMS TO NEXT DAY',
'             SELECT COUNT(1) INTO V_CNT2',
'             FROM EDC_CRF_ONSD661',
'             WHERE ONSD_STATUS =''Ongoing''',
'             AND PATIENT_DIARY_ID = V_LAST_DIARY_ID;',
'          ',
'             IF V_CNT2 > 0 THEN',
'             ',
'                V_PK_ID1 := 1;',
'          ',
'                SELECT NVL(MAX(ONS661_ID),0) + 1 INTO V_PK_ID FROM EDC_CRF_ONS661;',
'            ',
'                SELECT MAX(PATIENT_DIARY_ID) INTO V_PATIENT_DIARY_ID',
'                FROM EDC_PATIENT_DIARY',
'                WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID;',
'',
'                INSERT INTO EDC_CRF_ONS661( ONS661_ID, STUDY_ID, PATIENT_DIARY_ID, SECTION_STATUS, ONSQUES, CREATED_BY, CREATED_ON)',
'                VALUES(V_PK_ID , 661, V_PATIENT_DIARY_ID, 2, ''Yes'',UPPER(:APP_USER_NAME),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''));',
'                COMMIT;',
'                ',
'                select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                values(v_audit_id, ''EDC_CRF_ONS661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,509,''ONSQUES'',NULL,''Yes'',''INSERT'',',
'                UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                commit;',
'                ',
'                select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                values(v_audit_id, ''EDC_CRF_ONS661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,509,''SECTION_STATUS'',NULL,2,''INSERT'',',
'                UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                commit;',
'            ',
'                FOR J IN (SELECT ONSD661_ID, ONSDCOM ,ONSD_STDT, ONSDSTTM, ONSD_STATUS, ONSD_ENDT,ONSDENDTM FROM EDC_CRF_ONSD661',
'                WHERE ONSD_STATUS =''Ongoing'' AND PATIENT_DIARY_ID = V_LAST_DIARY_ID ORDER BY 1) LOOP',
'',
'                  SELECT NVL(MAX(ONSD661_ID),0) + 1 INTO V_PK_ID',
'                  FROM EDC_CRF_ONSD661;',
'',
'                  INSERT INTO EDC_CRF_ONSD661( ONSD661_ID, STUDY_ID, PATIENT_DIARY_ID, SECTION_STATUS, ONSD_SRNO, ONSDCOM ,ONSD_STDT, ONSDSTTM, ONSD_STATUS, ONSD_ENDT,ONSDENDTM, CREATED_BY, CREATED_ON)',
'                  VALUES(V_PK_ID , 661, V_PATIENT_DIARY_ID, 2, V_PK_ID1, J.ONSDCOM , J.ONSD_STDT, J.ONSDSTTM, J.ONSD_STATUS, J.ONSD_ENDT, J.ONSDENDTM,',
'                        UPPER(:APP_USER_NAME),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''));',
'',
'                  COMMIT;',
'                  ',
'                  select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                  insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                  USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                  values(v_audit_id, ''EDC_CRF_ONSD661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''SECTION_STATUS'',NULL,2,''INSERT'',',
'                  UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                  commit;',
'                  ',
'                  select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                  insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                  USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                  values(v_audit_id, ''EDC_CRF_ONSD661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''ONSD_SRNO'',NULL,V_PK_ID1,''INSERT'',',
'                  UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                  commit;',
'                  ',
'                  select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                  insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                  USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                  values(v_audit_id, ''EDC_CRF_ONSD661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''ONSDCOM'',NULL,J.ONSDCOM,''INSERT'',',
'                  UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                  commit;',
'                  ',
'                  select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                  insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                  USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                  values(v_audit_id, ''EDC_CRF_ONSD661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''ONSD_STDT'',NULL,TO_CHAR(J.ONSD_STDT,''DD-MON-YYYY''),''INSERT'',',
'                  UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                  commit;',
'                  ',
'                  select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                  insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                  USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                  values(v_audit_id, ''EDC_CRF_ONSD661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''ONSDSTTM'',NULL,TO_CHAR(J.ONSDSTTM,''HH24:MI''),''INSERT'',',
'                  UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                  commit;',
'                  ',
'                  select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                  insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                  USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                  values(v_audit_id, ''EDC_CRF_ONSD661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''ONSD_STATUS'',NULL,J.ONSD_STATUS,''INSERT'',',
'                  UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                  commit;',
'                  ',
'                  select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                  insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                  USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                  values(v_audit_id, ''EDC_CRF_ONSD661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''ONSD_ENDT'',NULL,TO_CHAR(J.ONSD_ENDT,''DD-MON-YYYY''),''INSERT'',',
'                  UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                  commit;',
'                  ',
'                  select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'                  insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'                  USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'                  values(v_audit_id, ''EDC_CRF_ONSD661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''ONSDENDTM'',NULL,TO_CHAR(J.ONSDENDTM,''HH24:MI''),''INSERT'',',
'                  UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'                  commit;',
'                ',
'                  V_PK_ID1 := V_PK_ID1 + 1;',
'    ',
'                END LOOP;',
'          ',
'           END IF;',
'           ',
'        END IF;',
'          ',
'        IF UPPER(:APP_EDC_SCHEDULE_NAME) NOT LIKE ''%MORNING%'' OR UPPER(:APP_EDC_SCHEDULE_NAME) NOT LIKE ''%EVENING%'' THEN',
'        ',
'          SELECT MAX(PATIENT_DIARY_ID) INTO V_LAST_DIARY_ID',
'          FROM EDC_PATIENT_DIARY',
'          WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID',
'          AND UPPER(SCHEDULE_TITLE) NOT LIKE ''%MORNING%''',
'          AND UPPER(SCHEDULE_TITLE) NOT LIKE ''%EVENING%''',
'          AND PATIENT_DIARY_ID != V_PATIENT_DIARY_ID1;',
'          ',
'          --FOR CARRYING FORWARD COMPLAINTS TO NEXT DAY',
'          SELECT COUNT(1) INTO V_CNT2',
'          FROM EDC_CRF_OCOMPDET661',
'          WHERE OCOMPDET_ENDT IS NULL',
'          AND PATIENT_DIARY_ID = V_LAST_DIARY_ID;',
'          ',
'          IF V_CNT2 > 0 THEN',
'          ',
'            V_PK_ID1 := 1;',
'          ',
'            SELECT NVL(MAX(OCOMP661_ID),0) + 1 INTO V_PK_ID FROM EDC_CRF_OCOMP661;',
'            ',
'            SELECT MAX(PATIENT_DIARY_ID) INTO V_PATIENT_DIARY_ID',
'            FROM EDC_PATIENT_DIARY',
'            WHERE PATIENT_PROFILE_ID = :APP_PATIENT_PROFILE_ID;',
'            ',
'            INSERT INTO EDC_CRF_OCOMP661( OCOMP661_ID, STUDY_ID, PATIENT_DIARY_ID, SECTION_STATUS, OCOMPQUES, CREATED_BY, CREATED_ON)',
'            VALUES(V_PK_ID , 661, V_PATIENT_DIARY_ID, 2, ''Yes'',UPPER(:APP_USER_NAME),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''));',
'            COMMIT;',
'            ',
'            select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'            insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'            USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'            values(v_audit_id, ''EDC_CRF_OCOMP661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,509,''OCOMPQUES'',NULL,''Yes'',''INSERT'',',
'            UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'            commit;',
'            ',
'            select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'            insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'            USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'            values(v_audit_id, ''EDC_CRF_OCOMP661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,509,''SECTION_STATUS'',NULL,2,''INSERT'',',
'            UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'            commit;',
'            ',
'            FOR J IN (SELECT OCOMPDET661_ID, COMPSRNO, COMPDESC, COMPYN, COMPWORYN, OCOMPDET_STDT, COMPDT, OCOMPDET_ENDT, COMPTM FROM EDC_CRF_OCOMPDET661',
'            WHERE OCOMPDET_ENDT IS NULL AND PATIENT_DIARY_ID = V_LAST_DIARY_ID ORDER BY 1) LOOP',
'            ',
'              SELECT NVL(MAX(OCOMPDET661_ID),0) + 1 INTO V_PK_ID',
'              FROM EDC_CRF_OCOMPDET661;',
'            ',
'              INSERT INTO EDC_CRF_OCOMPDET661( OCOMPDET661_ID, STUDY_ID, PATIENT_DIARY_ID, SECTION_STATUS, COMPSRNO, COMPDESC, COMPYN, COMPWORYN, OCOMPDET_STDT, COMPDT, OCOMPDET_ENDT, COMPTM, CREATED_BY, CREATED_ON)',
'              VALUES(V_PK_ID , 661, V_PATIENT_DIARY_ID, 2, V_PK_ID1, J.COMPDESC, J.COMPYN, J.COMPWORYN, J.OCOMPDET_STDT, J.COMPDT, J.OCOMPDET_ENDT, J.COMPTM,',
'                    UPPER(:APP_USER_NAME),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''));',
'              ',
'              COMMIT;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''SECTION_STATUS'',NULL,2,''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''COMPSRNO'',NULL,V_PK_ID1,''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''COMPDESC'',NULL,J.COMPDESC,''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''COMPYN'',NULL,J.COMPYN,''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''COMPWORYN'',NULL,J.COMPWORYN,''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''OCOMPDET_STDT'',NULL,TO_CHAR(J.OCOMPDET_STDT,''DD-MON-YYYY''),''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''COMPDT'',NULL,TO_CHAR(J.COMPDT,''HH24:MI''),''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''OCOMPDET_ENDT'',NULL,TO_CHAR(J.OCOMPDET_ENDT,''DD-MON-YYYY''),''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              select nvl(max(audit_log_id),0)+1 into v_audit_id from audit_trail;',
'            ',
'              insert into AUDIT_TRAIL(AUDIT_LOG_ID, TABLE_NAME,STUDY_ID,STUDY_SITE_ID,PATIENT_PROFILE_ID,PATIENT_DIARY_ID,PAGE_NO,COLUMN_NAME,OLD_VALUE,NEW_VALUE,ACTION,',
'              USERNAME,LOG_TIMESTAMP,REASON,TABLE_PK_VALUE) ',
'              values(v_audit_id, ''EDC_CRF_OCOMPDET661'',661,V_STUDY_SITE_ID,:APP_PATIENT_PROFILE_ID,V_PATIENT_DIARY_ID,510,''COMPTM'',NULL,TO_CHAR(J.COMPTM,''HH24:MI''),''INSERT'',',
'              UPPER(:APP_USER),TO_DATE(TO_CHAR(LOCALTIMESTAMP,''DD-MON-YYYY HH24:MI:SS''),''DD-MON-YYYY HH24:MI:SS''),NULL,V_PK_ID);',
'              commit;',
'              ',
'              V_PK_ID1 := V_PK_ID1 + 1;',
'            ',
'            END LOOP;',
'          ',
'          END IF;',
'        ',
'        END IF;',
'         ',
'    ELSE',
'         ',
'         SELECT MAX(PATIENT_DIARY_ID) INTO v_patient_diary FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID=:APP_PATIENT_PROFILE_ID;',
'    ',
'    END IF;',
'    ',
'    /*IF V_PAGE_NO = 100 THEN',
'        APEX_UTIL.REDIRECT_URL(''f?p='' || v(''APP_ID'') || '':100:'' || v(''SESSION'')||''::NO:100:APP_EDC_SCHEDULE_NAME,APP_PATIENT_PROFILE_ID,APP_EDC_STUDY_SITE_ID,P100_CRF_ID:''||:APP_EDC_SCHEDULE_NAME||'',''||:APP_PATIENT_PROFILE_ID||'',''||V_STUDY_SITE_ID||'''
||',''||V_CRF_ID);',
'    ELSIF V_PAGE_NO = 100 THEN',
'        APEX_UTIL.REDIRECT_URL(''f?p='' || v(''APP_ID'') || '':100:'' || v(''SESSION'')||''::NO:100:APP_EDC_SCHEDULE_NAME,APP_PATIENT_PROFILE_ID,APP_EDC_STUDY_SITE_ID,P100_CRF_ID:''||:APP_EDC_SCHEDULE_NAME||'',''||:APP_PATIENT_PROFILE_ID||'',''||V_STUDY_SITE_ID||'''
||',''||V_CRF_ID);',
'    END IF;*/',
'    ',
'    APEX_UTIL.REDIRECT_URL(''f?p='' || v(''APP_ID'') || '':45:'' || v(''SESSION'')||''::NO:100:APP_EDC_SCHEDULE_NAME,APP_PATIENT_PROFILE_ID,APP_EDC_STUDY_SITE_ID:''||:APP_EDC_SCHEDULE_NAME||'',''||:APP_PATIENT_PROFILE_ID||'',''||V_STUDY_SITE_ID);',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>4072823132821996210
);
wwv_flow_imp.component_end;
end;
/
