prompt --application/pages/page_00119
begin
--   Manifest
--     PAGE: 00119
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>666903967469575309
,p_default_application_id=>10021010
,p_default_id_offset=>759714394172364641
,p_default_owner=>'SUN_21010_DEV'
);
wwv_flow_imp_page.create_page(
 p_id=>119
,p_tab_set=>'TS1'
,p_name=>'ePRO - IP Compliance Report'
,p_step_title=>'ePRO - IP Compliance Report'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_page_template_options=>'#DEFAULT#'
,p_help_text=>'No help is available for this page.'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(2445839165105484583)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(11045179264140407886)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_new_grid_row=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(2445839101706484582)
,p_plug_name=>'Colour Code'
,p_parent_plug_id=>wwv_flow_imp.id(2445839165105484583)
,p_region_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-left:10px;"'
,p_plug_template=>wwv_flow_imp.id(11045179264140407886)
,p_plug_display_sequence=>30
,p_plug_display_point=>'SUB_REGIONS'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<b style="font-size:15px;">Colour Code:</b><br><br><p style="font-size:15px; line-height: 1.5;"><b style="color:limegreen;">Green</b><b>: Number of tablets taken = As prescribed;&nbsp;&nbsp;&nbsp;&nbsp;</b><b style="color:gold;">Yellow</b><b>: Number'
||' of tablets taken <  As prescribed;&nbsp;&nbsp;&nbsp;&nbsp;</b><br><b style="color:orange;">Orange</b><b>: Number of tablets taken > As prescribed;&nbsp;&nbsp;&nbsp;&nbsp;</b><b style="color:orangered;">Red</b><b>: Data for the number of tablets take'
||'n is unavailable.</b></p>',
''))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11162703912003014795)
,p_plug_name=>'ePRO - IP Compliance Report'
,p_parent_plug_id=>wwv_flow_imp.id(2445839165105484583)
,p_region_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-left:10px;"'
,p_plug_template=>wwv_flow_imp.id(11045181488778407888)
,p_plug_display_sequence=>40
,p_plug_display_point=>'SUB_REGIONS'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT STUDY_SITE_ID, PATIENT_PROFILE_ID,',
'SCRNO, ',
'(SELECT DISPLAY_VALUE FROM EDC_LOV_VALUES WHERE LOV_ID = 36 AND STORED_VALUE = A.STATUS) "STATUS",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 3)) "DAY1_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 3)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 3)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 3)) < 9 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 3)) > 9 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 3)) = 9 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY1_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 4)) "DAY1_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 4)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 4)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 4)) < 9 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 4)) > 9 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 4)) = 9 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY1_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 5)) "DAY2_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 5)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 5)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 5)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 5)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 5)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY2_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 6)) "DAY2_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 6)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 6)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 6)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 6)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 6)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY2_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 7)) "DAY3_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 7)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 7)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 7)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 7)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 7)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY3_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 8)) "DAY3_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 8)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 8)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 8)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 8)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 8)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY3_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 9)) "DAY4_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 9)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 9)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 9)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 9)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 9)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY4_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 10)) "DAY4_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 10)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 10)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 10)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 10)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 10)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY4_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 11)) "DAY5_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 11)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 11)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 11)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 11)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 11)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY5_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 12)) "DAY5_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 12)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 12)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 12)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 12)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 12)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY5_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 13)) "DAY6_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 13)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 13)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 13)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 13)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 13)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY6_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 14)) "DAY6_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 14)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 14)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 14)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 14)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 14)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY6_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 15)) "DAY7_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 15)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 15)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 15)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 15)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 15)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY7_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 16)) "DAY7_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 16)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 16)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 16)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 16)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 16)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY7_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 17)) "DAY8_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 17)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 17)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 17)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 17)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 17)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY8_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 18)) "DAY8_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 18)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 18)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 18)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 18)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 18)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY8_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 19)) "DAY9_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 19)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 19)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 19)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 19)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 19)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY9_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 20)) "DAY9_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 20)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 20)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 20)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 20)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 20)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY9_DOSE2_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 21)) "DAY10_DOSE1",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 21)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 21)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 21)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 21)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 21)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY10_DOSE1_CLR",',
'',
'(SELECT SDMTAB FROM EDC_CRF_SMA661 ',
'WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID ',
'AND SCHEDULE_ID = 22)) "DAY10_DOSE2",',
'',
'CASE WHEN (SELECT COUNT(1) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 22)) = 0 THEN ''data-style="background-color:#ffffff00"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 22)) IS NULL THEN ''data-style="background-color:red"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 22)) < 4 THEN ''data-style="background-color:yellow"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 22)) > 4 THEN ''data-style="background-color:orange"''',
'WHEN (SELECT SDMTAB FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID=(SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND SCHEDULE_ID = 22)) = 4 THEN ''data-style="background-color:limegreen"'' ',
'END "DAY10_DOSE2_CLR",',
'',
'ROUND(((SELECT SUM(SDMTAB) FROM EDC_CRF_SMA661 WHERE PATIENT_DIARY_ID IN (SELECT PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID))/90)*100,2) "IP_COMP_PERCT"',
'',
'FROM EDC_PATIENT_PROFILE A',
'where a.study_site_id = DECODE(:P119_SITES,999999,a.study_site_id,:P119_SITES)',
'AND EPRO_STATUS IS NOT NULL',
'ORDER BY STUDY_SITE_ID, PATIENT_PROFILE_ID',
''))
,p_plug_source_type=>'NATIVE_IR'
,p_ajax_items_to_submit=>'APP_EDC_STUDY_ID,APP_USER_NAME,APP_EDC_USER_TYPE,APP_EDC_USER_ID,APP_EDC_ROLE_ID,APP_EDC_ROLE_LEVEL,P119_SITES'
,p_prn_content_disposition=>'ATTACHMENT'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(11162704005193014795)
,p_name=>'Subject Visits'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_max_rows_per_page=>'20'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y_OF_Z'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'NIKHIL.BUTANI'
,p_internal_uid=>8717209266313195547
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2697934292583425038)
,p_db_column_name=>'PATIENT_PROFILE_ID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Patient Profile Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2697934676202425038)
,p_db_column_name=>'STUDY_SITE_ID'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Site'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(11051796963439023522)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2697935083664425039)
,p_db_column_name=>'SCRNO'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Screening<br/>Number'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766083071416588)
,p_db_column_name=>'STATUS'
,p_display_order=>15
,p_column_identifier=>'BB'
,p_column_label=>'Status'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766145863416589)
,p_db_column_name=>'DAY1_DOSE1'
,p_display_order=>25
,p_column_identifier=>'BC'
,p_column_label=>'Day 1 Dose 1'
,p_column_html_expression=>'<span #DAY1_DOSE1_CLR#>#DAY1_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766239305416590)
,p_db_column_name=>'DAY1_DOSE1_CLR'
,p_display_order=>35
,p_column_identifier=>'BD'
,p_column_label=>'Day1 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766371756416591)
,p_db_column_name=>'DAY1_DOSE2'
,p_display_order=>45
,p_column_identifier=>'BE'
,p_column_label=>'Day 1 Dose 2'
,p_column_html_expression=>'<span #DAY1_DOSE2_CLR#>#DAY1_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766506967416592)
,p_db_column_name=>'DAY1_DOSE2_CLR'
,p_display_order=>55
,p_column_identifier=>'BF'
,p_column_label=>'Day1 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766541368416593)
,p_db_column_name=>'DAY2_DOSE1'
,p_display_order=>65
,p_column_identifier=>'BG'
,p_column_label=>'Day 2 Dose 1'
,p_column_html_expression=>'<span #DAY2_DOSE1_CLR#>#DAY2_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766711751416594)
,p_db_column_name=>'DAY2_DOSE1_CLR'
,p_display_order=>75
,p_column_identifier=>'BH'
,p_column_label=>'Day2 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766743620416595)
,p_db_column_name=>'DAY2_DOSE2'
,p_display_order=>85
,p_column_identifier=>'BI'
,p_column_label=>'Day 2 Dose 2'
,p_column_html_expression=>'<span #DAY2_DOSE2_CLR#>#DAY2_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445766882120416596)
,p_db_column_name=>'DAY2_DOSE2_CLR'
,p_display_order=>95
,p_column_identifier=>'BJ'
,p_column_label=>'Day2 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767019517416597)
,p_db_column_name=>'DAY3_DOSE1'
,p_display_order=>105
,p_column_identifier=>'BK'
,p_column_label=>'Day 3 Dose 1'
,p_column_html_expression=>'<span #DAY3_DOSE1_CLR#>#DAY3_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767106592416598)
,p_db_column_name=>'DAY3_DOSE1_CLR'
,p_display_order=>115
,p_column_identifier=>'BL'
,p_column_label=>'Day3 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767168748416599)
,p_db_column_name=>'DAY3_DOSE2'
,p_display_order=>125
,p_column_identifier=>'BM'
,p_column_label=>'Day 3 Dose 2'
,p_column_html_expression=>'<span #DAY3_DOSE2_CLR#>#DAY3_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767304528416600)
,p_db_column_name=>'DAY3_DOSE2_CLR'
,p_display_order=>135
,p_column_identifier=>'BN'
,p_column_label=>'Day3 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767358330416601)
,p_db_column_name=>'DAY4_DOSE1'
,p_display_order=>145
,p_column_identifier=>'BO'
,p_column_label=>'Day 4 Dose 1'
,p_column_html_expression=>'<span #DAY4_DOSE1_CLR#>#DAY4_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767444490416602)
,p_db_column_name=>'DAY4_DOSE1_CLR'
,p_display_order=>155
,p_column_identifier=>'BP'
,p_column_label=>'Day4 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767582917416603)
,p_db_column_name=>'DAY4_DOSE2'
,p_display_order=>165
,p_column_identifier=>'BQ'
,p_column_label=>'Day 4 Dose 2'
,p_column_html_expression=>'<span #DAY4_DOSE2_CLR#>#DAY4_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767719035416604)
,p_db_column_name=>'DAY4_DOSE2_CLR'
,p_display_order=>175
,p_column_identifier=>'BR'
,p_column_label=>'Day4 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767804389416605)
,p_db_column_name=>'DAY5_DOSE1'
,p_display_order=>185
,p_column_identifier=>'BS'
,p_column_label=>'Day 5 Dose 1'
,p_column_html_expression=>'<span #DAY5_DOSE1_CLR#>#DAY5_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767894948416606)
,p_db_column_name=>'DAY5_DOSE1_CLR'
,p_display_order=>195
,p_column_identifier=>'BT'
,p_column_label=>'Day5 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445767972271416607)
,p_db_column_name=>'DAY5_DOSE2'
,p_display_order=>205
,p_column_identifier=>'BU'
,p_column_label=>'Day 5 Dose 2'
,p_column_html_expression=>'<span #DAY5_DOSE2_CLR#>#DAY5_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768055071416608)
,p_db_column_name=>'DAY5_DOSE2_CLR'
,p_display_order=>215
,p_column_identifier=>'BV'
,p_column_label=>'Day5 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768154342416609)
,p_db_column_name=>'DAY6_DOSE1'
,p_display_order=>225
,p_column_identifier=>'BW'
,p_column_label=>'Day 6 Dose 1'
,p_column_html_expression=>'<span #DAY6_DOSE1_CLR#>#DAY6_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768253887416610)
,p_db_column_name=>'DAY6_DOSE1_CLR'
,p_display_order=>235
,p_column_identifier=>'BX'
,p_column_label=>'Day6 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768378003416611)
,p_db_column_name=>'DAY6_DOSE2'
,p_display_order=>245
,p_column_identifier=>'BY'
,p_column_label=>'Day 6 Dose 2'
,p_column_html_expression=>'<span #DAY6_DOSE2_CLR#>#DAY6_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768478942416612)
,p_db_column_name=>'DAY6_DOSE2_CLR'
,p_display_order=>255
,p_column_identifier=>'BZ'
,p_column_label=>'Day6 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768600789416613)
,p_db_column_name=>'DAY7_DOSE1'
,p_display_order=>265
,p_column_identifier=>'CA'
,p_column_label=>'Day 7 Dose 1'
,p_column_html_expression=>'<span #DAY7_DOSE1_CLR#>#DAY7_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768696534416614)
,p_db_column_name=>'DAY7_DOSE1_CLR'
,p_display_order=>275
,p_column_identifier=>'CB'
,p_column_label=>'Day7 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768813311416615)
,p_db_column_name=>'DAY7_DOSE2'
,p_display_order=>285
,p_column_identifier=>'CC'
,p_column_label=>'Day 7 Dose 2'
,p_column_html_expression=>'<span #DAY7_DOSE2_CLR#>#DAY7_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768851715416616)
,p_db_column_name=>'DAY7_DOSE2_CLR'
,p_display_order=>295
,p_column_identifier=>'CD'
,p_column_label=>'Day7 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445768947125416617)
,p_db_column_name=>'DAY8_DOSE1'
,p_display_order=>305
,p_column_identifier=>'CE'
,p_column_label=>'Day 8 Dose 1'
,p_column_html_expression=>'<span #DAY8_DOSE1_CLR#>#DAY8_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445769025957416618)
,p_db_column_name=>'DAY8_DOSE1_CLR'
,p_display_order=>315
,p_column_identifier=>'CF'
,p_column_label=>'Day8 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445769142764416619)
,p_db_column_name=>'DAY8_DOSE2'
,p_display_order=>325
,p_column_identifier=>'CG'
,p_column_label=>'Day 8 Dose 2'
,p_column_html_expression=>'<span #DAY8_DOSE2_CLR#>#DAY8_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445769315388416620)
,p_db_column_name=>'DAY8_DOSE2_CLR'
,p_display_order=>335
,p_column_identifier=>'CH'
,p_column_label=>'Day8 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445769399584416621)
,p_db_column_name=>'DAY9_DOSE1'
,p_display_order=>345
,p_column_identifier=>'CI'
,p_column_label=>'Day 9 Dose 1'
,p_column_html_expression=>'<span #DAY9_DOSE1_CLR#>#DAY9_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445838066470484572)
,p_db_column_name=>'DAY9_DOSE1_CLR'
,p_display_order=>355
,p_column_identifier=>'CJ'
,p_column_label=>'Day9 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445838156139484573)
,p_db_column_name=>'DAY9_DOSE2'
,p_display_order=>365
,p_column_identifier=>'CK'
,p_column_label=>'Day 9 Dose 2'
,p_column_html_expression=>'<span #DAY9_DOSE2_CLR#>#DAY9_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445838289701484574)
,p_db_column_name=>'DAY9_DOSE2_CLR'
,p_display_order=>375
,p_column_identifier=>'CL'
,p_column_label=>'Day9 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445838383809484575)
,p_db_column_name=>'DAY10_DOSE1'
,p_display_order=>385
,p_column_identifier=>'CM'
,p_column_label=>'Day 10 Dose 1'
,p_column_html_expression=>'<span #DAY10_DOSE1_CLR#>#DAY10_DOSE1#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445838454110484576)
,p_db_column_name=>'DAY10_DOSE1_CLR'
,p_display_order=>395
,p_column_identifier=>'CN'
,p_column_label=>'Day10 Dose1 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445838540717484577)
,p_db_column_name=>'DAY10_DOSE2'
,p_display_order=>405
,p_column_identifier=>'CO'
,p_column_label=>'Day 10 Dose 2'
,p_column_html_expression=>'<span #DAY10_DOSE2_CLR#>#DAY10_DOSE2#</span>'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445838685821484578)
,p_db_column_name=>'DAY10_DOSE2_CLR'
,p_display_order=>415
,p_column_identifier=>'CP'
,p_column_label=>'Day10 Dose2 Clr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2445838729241484579)
,p_db_column_name=>'IP_COMP_PERCT'
,p_display_order=>425
,p_column_identifier=>'CQ'
,p_column_label=>'IP Compliance %'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(11162710822159015728)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'2524419'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_display_rows=>20
,p_report_columns=>'STUDY_SITE_ID:SCRNO:SECTION_:STATUS:DAY1_DOSE1:DAY1_DOSE1_CLR:DAY1_DOSE2:DAY1_DOSE2_CLR:DAY2_DOSE1:DAY2_DOSE1_CLR:DAY2_DOSE2:DAY2_DOSE2_CLR:DAY3_DOSE1:DAY3_DOSE1_CLR:DAY3_DOSE2:DAY3_DOSE2_CLR:DAY4_DOSE1:DAY4_DOSE1_CLR:DAY4_DOSE2:DAY4_DOSE2_CLR:DAY5_D'
||'OSE1:DAY5_DOSE1_CLR:DAY5_DOSE2:DAY5_DOSE2_CLR:DAY6_DOSE1:DAY6_DOSE1_CLR:DAY6_DOSE2:DAY6_DOSE2_CLR:DAY7_DOSE1:DAY7_DOSE1_CLR:DAY7_DOSE2:DAY7_DOSE2_CLR:DAY8_DOSE1:DAY8_DOSE1_CLR:DAY8_DOSE2:DAY8_DOSE2_CLR:DAY9_DOSE1:DAY9_DOSE1_CLR:DAY9_DOSE2:DAY9_DOSE2_'
||'CLR:DAY10_DOSE1:DAY10_DOSE1_CLR:DAY10_DOSE2:DAY10_DOSE2_CLR:IP_COMP_PERCT'
,p_sort_column_1=>'PATIENT_PROFILE_ID'
,p_sort_direction_1=>'ASC'
,p_sort_column_2=>'PATIENT_DIARY_ID'
,p_sort_direction_2=>'ASC'
,p_sort_column_3=>'0'
,p_sort_direction_3=>'ASC'
,p_sort_column_4=>'0'
,p_sort_direction_4=>'ASC'
,p_sort_column_5=>'0'
,p_sort_direction_5=>'ASC'
,p_sort_column_6=>'0'
,p_sort_direction_6=>'ASC'
,p_break_on=>'STUDY_SITE_ID:0:0:0:0:0'
,p_break_enabled_on=>'STUDY_SITE_ID:0:0:0:0:0'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11162703344061014793)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(11045179465801407886)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(11045189164405407923)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(11045187162360407898)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11162731029923119755)
,p_plug_name=>'Study Reports List'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-right:5px;"'
,p_plug_template=>wwv_flow_imp.id(11045181058343407888)
,p_plug_display_sequence=>10
,p_list_id=>wwv_flow_imp.id(11061305288454172215)
,p_plug_source_type=>'NATIVE_LIST'
,p_list_template_id=>wwv_flow_imp.id(11061512871844880215)
,p_plug_query_headings_type=>'QUERY_COLUMNS'
,p_plug_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_plug_query_show_nulls_as=>' - '
,p_pagination_display_position=>'BOTTOM_RIGHT'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(2697937085986425057)
,p_name=>'P119_SITES'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(11162703912003014795)
,p_prompt=>'Sites'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select d, r from (SELECT a.site_number || '' ('' || FIRST_NAME || '' '' || LAST_NAME || '' - '' || b.invname || '')'' D',
'     , A.STUDY_SITE_ID R, ''1'' s',
'  FROM EDC_STUDY_SITES A,',
'       EDC_SITES B',
' WHERE A.SITE_ID = B.SITE_ID',
'   AND A.STUDY_ID = :APP_EDC_STUDY_ID',
'   AND EDC_AUTH_PKG.CHECK_STUDY_SITE_ACCESS(A.STUDY_SITE_ID) <> 0',
'union',
'select ''All Sites'' D, 999999 r, ''0'' s',
'from dual',
'order by s, d)'))
,p_lov_display_null=>'YES'
,p_lov_null_text=>'--Select--'
,p_cHeight=>1
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_imp.id(11045185769059407896)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'NO'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'SUBMIT'
,p_attribute_03=>'Y'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(2445838858536484580)
,p_name=>'Coloring_Cells_Report Region'
,p_event_sequence=>30
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_imp.id(11162703912003014795)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterrefresh'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(2445838947627484581)
,p_event_id=>wwv_flow_imp.id(2445838858536484580)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'apex.jQuery("span[data-style]").each(',
'  function()',
'  { ',
'    apex.jQuery(this).',
'      parent().attr( ''style''',
'                   , apex.jQuery(this).attr(''data-style'')',
'                   ); ',
'  }',
');'))
);
wwv_flow_imp.component_end;
end;
/
