prompt --application/pages/page_00109
begin
--   Manifest
--     PAGE: 00109
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>666903967469575309
,p_default_application_id=>10021010
,p_default_id_offset=>759714394172364641
,p_default_owner=>'SUN_21010_DEV'
);
wwv_flow_imp_page.create_page(
 p_id=>109
,p_tab_set=>'TS1'
,p_name=>'ePRO - Query Report'
,p_step_title=>'ePRO - Query Report'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_page_template_options=>'#DEFAULT#'
,p_help_text=>'No help is available for this page.'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(10421716565432622827)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(11045179465801407886)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(11045189164405407923)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(11045187162360407898)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(10421717133374622829)
,p_plug_name=>'ePRO - Query Report'
,p_region_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-left:10px;"'
,p_plug_template=>wwv_flow_imp.id(11045181488778407888)
,p_plug_display_sequence=>40
,p_plug_new_grid_row=>false
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT PP.PTINTL "Subject Initial",',
'  V.SCHEDULE_TITLE "Visit Title",',
'  S.DISP_SCHEDULE_NAME "Schedule Name",',
'  PP.SCRNO "Screening No.",',
'  PP.RANDOMNO "Randomization No.",',
'  Q.QRY_ID "Query#",',
'  Q.QRY_ID "Query1#",',
'  CASE WHEN Q.PAGE_ID NOT IN (510) THEN',
'  ''f?p=&APP_ID.:''||q.page_id||'':''||:APP_SESSION||''::NO::APP_EDC_PATIENT_DIARY_ID,APP_PATIENT_PROFILE_ID,APP_EDC_SCHEDULE_NAME,P''||Q.PAGE_ID||''_CRF_ID:''||V.PATIENT_DIARY_ID||'',''||V.PATIENT_PROFILE_ID||'',''||V.SCHEDULE_TITLE||'',''||CM.CRF_ID',
'  WHEN Q.PAGE_ID IN (510) THEN ',
'  ''f?p=&APP_ID.:''||q.page_id||'':''||:APP_SESSION||''::NO::APP_EDC_PATIENT_DIARY_ID,APP_PATIENT_PROFILE_ID,APP_EDC_SCHEDULE_NAME,P''||Q.PAGE_ID||''_CRF_ID,P510_CRF_TABLE_PK_VAL,P509_CRF_ID:''||V.PATIENT_DIARY_ID||'',''||V.PATIENT_PROFILE_ID||'',''||V.SCHEDULE_'
||'TITLE||'',''||CM.CRF_ID||'',''||Q.TBL_PK_ID||'',''||CM.PARENT_PAGE',
'  END "QRY_LINK",',
'  CASE WHEN Q.PAGE_ID IN (100,510) THEN',
'  --''javascript:popupURL(''''f?p=&APP_ID.:6:''||:APP_SESSION||''.::&DEBUG.:6:P6_PATIENT_DIARY_ID,P6_PAGE_ID,P6_CRF_ID,P6_TBL_PK_ID:''||V.PATIENT_DIARY_ID||'',''||Q.PAGE_ID||'',''||CM.CRF_ID||'',''||Q.TBL_PK_ID||'''''')''',
'  ''javascript:popupURL(''''f?p=&APP_ID.:4:''||:APP_SESSION||''.::&DEBUG.:4:P4_QRY_ID,P4_REQUEST_FROM,P4_QRY_STATUS,P4_AUTO_FLAG,P4_CRF_ID:''||Q.QRY_ID||'',''||Q.PAGE_ID||'',''||Q.QRY_STATUS||'',''||Q.AUTO_FLAG||'',''||CM.CRF_ID||'''''')''',
'  end "QRY_LINK1",',
'  V.SCHEDULE_NUMBER,',
'  Q.STUDY_ID,',
'  Q.PATIENT_DIARY_ID,',
'  Q.PAGE_ID "Page Name",',
'  (SELECT ITEM_LABEL FROM EDC_CRF_ITEMS WHERE COLUMN_NAME = Q.ITEM_NAME AND CRF_ID = CM.CRF_ID) "Item Name",',
'  Q.QRY_DESC "Query Description",',
'  Q.QRY_STATUS "Query Status",',
'  Q.QRY_RESPONSE "Query Response",',
'  Q.CREATED_BY"Created By",',
'  to_char(Q.CREATED_DT,''DD-MON-YYYY HH24:MI'') CREATED_DT,',
'  Q.UPDATED_BY"Updated By",',
'  to_char(Q.UPDATED_DT ,''DD-MON-YYYY HH24:MI'') UPDATED_DT,',
'  PP.PATIENT_PROFILE_ID,',
'  Q.PAGE_ID,',
'  pp.study_site_id "SITE NAME",',
'  DECODE(q.auto_flag,''A'',''System'',''User'') "Generated By",',
'  nvl(cm.table_pk_field,''P''||cm.crf_page_no||''_''||Cm.Crf_Table_Pk_Col) "PK",',
'  Q.TBL_PK_ID,',
'  CM.CRF_ID "CRF NAME",',
'  CM.CRF_ID "CRF_ID1",',
'    CASE WHEN Q.QRY_STATUS =''Closed'' THEN',
'  (SELECT TO_DATE(TO_CHAR(Q.UPDATED_DT,''DD-MON-YYYY''),''DD-MM-YY'') - TO_DATE(TO_CHAR(A.CREATED_ON,''DD-MON-YYYY''),''DD-MM-YY'') ',
'  FROM EDC_CRF_QUERIES_DETAILS A',
'  WHERE A.QRY_DETAIL_ID = (SELECT MIN(QRY_DETAIL_ID) FROM EDC_CRF_QUERIES_DETAILS WHERE QRY_ID = Q.QRY_ID))',
'  ELSE',
'  TO_DATE(SYSDATE,''DD-MM-YY'') - TO_DATE(TO_CHAR(Q.CREATED_DT,''DD-MON-YYYY''),''DD-MM-YY'') ',
'  END "NO_OF_DAYS"',
'FROM EDC_CRF_QUERIES Q, EDC_PATIENT_DIARY V, EDC_PATIENT_PROFILE PP, edc_crf_master cm, EDC_PATIENT_SCHEDULE_PARAMS s',
'WHERE V.PATIENT_DIARY_ID = Q.PATIENT_DIARY_ID',
'AND PP.PATIENT_PROFILE_ID = V.PATIENT_PROFILE_ID',
'AND S.SCHEDULE_NAME = V.SCHEDULE_TITLE',
'AND q.crf_id = Cm.Crf_id',
'AND cm.crf_page_no IN (100,509,510)',
'AND cm.study_id = q.study_id',
'AND Q.STUDY_ID = :APP_EDC_STUDY_ID',
'AND PP.STUDY_SITE_ID = decode(:P109_SITE,999999,PP.STUDY_SITE_ID,:P109_SITE)'))
,p_plug_source_type=>'NATIVE_IR'
,p_ajax_items_to_submit=>'APP_ID,APP_EDC_STUDY_ID,APP_EDC_ROLE_ID,APP_USER_NAME,APP_EDC_USER_TYPE,APP_EDC_USER_ID,APP_EDC_ROLE_LEVEL,P109_SITE'
,p_prn_content_disposition=>'ATTACHMENT'
,p_plug_comment=>',APP_EDC_SITE_TYPE'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(10421717226564622829)
,p_name=>'Subject Visits'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_max_rows_per_page=>'20'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y_OF_Z'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'NIKHIL.BUTANI'
,p_internal_uid=>7976222487684803581
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2689486026438813726)
,p_db_column_name=>'PATIENT_PROFILE_ID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Patient Profile Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_display_condition_type=>'NEVER'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682958327813587474)
,p_db_column_name=>'Subject Initial'
,p_display_order=>11
,p_column_identifier=>'AN'
,p_column_label=>'Subject Initial'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682958343030587475)
,p_db_column_name=>'Visit Title'
,p_display_order=>21
,p_column_identifier=>'AO'
,p_column_label=>'Visit Title'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682958502459587476)
,p_db_column_name=>'Screening No.'
,p_display_order=>31
,p_column_identifier=>'AP'
,p_column_label=>'Screening No.'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682958636101587477)
,p_db_column_name=>'Randomization No.'
,p_display_order=>41
,p_column_identifier=>'AQ'
,p_column_label=>'Randomization No.'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682958730423587478)
,p_db_column_name=>'Query#'
,p_display_order=>51
,p_column_identifier=>'AR'
,p_column_label=>'View Data'
,p_column_link=>'#QRY_LINK#'
,p_column_linktext=>'#Query##'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_static_id=>'Query#'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682958749772587479)
,p_db_column_name=>'Query1#'
,p_display_order=>61
,p_column_identifier=>'AS'
,p_column_label=>'Query'
,p_column_link=>'#QRY_LINK1#'
,p_column_linktext=>'#Query1##'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682958927849587480)
,p_db_column_name=>'QRY_LINK'
,p_display_order=>71
,p_column_identifier=>'AT'
,p_column_label=>'Qry Link'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959019244587481)
,p_db_column_name=>'QRY_LINK1'
,p_display_order=>81
,p_column_identifier=>'AU'
,p_column_label=>'Qry Link1'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959145963587483)
,p_db_column_name=>'STUDY_ID'
,p_display_order=>101
,p_column_identifier=>'AW'
,p_column_label=>'Study Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959369814587485)
,p_db_column_name=>'Page Name'
,p_display_order=>121
,p_column_identifier=>'AY'
,p_column_label=>'Page Name'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959526780587486)
,p_db_column_name=>'Item Name'
,p_display_order=>131
,p_column_identifier=>'AZ'
,p_column_label=>'Item Name'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959623336587487)
,p_db_column_name=>'Query Description'
,p_display_order=>141
,p_column_identifier=>'BA'
,p_column_label=>'Query Description'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959664768587488)
,p_db_column_name=>'Query Status'
,p_display_order=>151
,p_column_identifier=>'BB'
,p_column_label=>'Query Status'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959789408587489)
,p_db_column_name=>'Query Response'
,p_display_order=>161
,p_column_identifier=>'BC'
,p_column_label=>'Query Response'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959879009587490)
,p_db_column_name=>'Created By'
,p_display_order=>171
,p_column_identifier=>'BD'
,p_column_label=>'Created By'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682959965508587491)
,p_db_column_name=>'CREATED_DT'
,p_display_order=>181
,p_column_identifier=>'BE'
,p_column_label=>'Created On'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682960042465587492)
,p_db_column_name=>'Updated By'
,p_display_order=>191
,p_column_identifier=>'BF'
,p_column_label=>'Updated By'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682960237964587493)
,p_db_column_name=>'UPDATED_DT'
,p_display_order=>201
,p_column_identifier=>'BG'
,p_column_label=>'Updated On'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682960248142587494)
,p_db_column_name=>'PAGE_ID'
,p_display_order=>211
,p_column_identifier=>'BH'
,p_column_label=>'Page Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682960339631587495)
,p_db_column_name=>'SITE NAME'
,p_display_order=>221
,p_column_identifier=>'BI'
,p_column_label=>'Site Name'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(2689760156027981202)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682960489936587496)
,p_db_column_name=>'Generated By'
,p_display_order=>231
,p_column_identifier=>'BJ'
,p_column_label=>'Generated By'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682960581596587497)
,p_db_column_name=>'PK'
,p_display_order=>241
,p_column_identifier=>'BK'
,p_column_label=>'Pk'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2682960720877587498)
,p_db_column_name=>'TBL_PK_ID'
,p_display_order=>251
,p_column_identifier=>'BL'
,p_column_label=>'Tbl Pk Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2689561260183918149)
,p_db_column_name=>'CRF NAME'
,p_display_order=>261
,p_column_identifier=>'BM'
,p_column_label=>'CRF Name'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(2689750734328953817)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2689561401800918150)
,p_db_column_name=>'CRF_ID1'
,p_display_order=>271
,p_column_identifier=>'BN'
,p_column_label=>'Crf Id1'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2689561460952918151)
,p_db_column_name=>'NO_OF_DAYS'
,p_display_order=>281
,p_column_identifier=>'BO'
,p_column_label=>'No Of Days'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2689563995148918176)
,p_db_column_name=>'SCHEDULE_NUMBER'
,p_display_order=>291
,p_column_identifier=>'BP'
,p_column_label=>'Schedule Number'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2689564041404918177)
,p_db_column_name=>'PATIENT_DIARY_ID'
,p_display_order=>301
,p_column_identifier=>'BQ'
,p_column_label=>'Patient Diary Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(2689992752087415896)
,p_db_column_name=>'Schedule Name'
,p_display_order=>311
,p_column_identifier=>'BR'
,p_column_label=>'Schedule Name'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(10421724043530623762)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'2439944'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_display_rows=>20
,p_report_columns=>'Screening No.:Subject Initial:Schedule Name:Query#:Query1#:SITE NAME:CRF NAME:Item Name:Query Description:Query Status:Query Response:Created By:CREATED_DT:Updated By:UPDATED_DT:Generated By:NO_OF_DAYS:'
,p_sort_column_1=>'SCRNO'
,p_sort_direction_1=>'ASC'
,p_sort_column_2=>'0'
,p_sort_direction_2=>'ASC'
,p_sort_column_3=>'0'
,p_sort_direction_3=>'ASC'
,p_sort_column_4=>'0'
,p_sort_direction_4=>'ASC'
,p_sort_column_5=>'0'
,p_sort_direction_5=>'ASC'
,p_sort_column_6=>'0'
,p_sort_direction_6=>'ASC'
,p_break_on=>'Screening No.:Subject Initial:Schedule Name:0:0:0'
,p_break_enabled_on=>'Screening No.:0:0:0:Subject Initial:Schedule Name'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(10421744251294727789)
,p_plug_name=>'Study Reports List'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-right:5px;"'
,p_plug_template=>wwv_flow_imp.id(11045181058343407888)
,p_plug_display_sequence=>10
,p_list_id=>wwv_flow_imp.id(11061305288454172215)
,p_plug_source_type=>'NATIVE_LIST'
,p_list_template_id=>wwv_flow_imp.id(11061512871844880215)
,p_plug_query_headings_type=>'QUERY_COLUMNS'
,p_plug_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_plug_query_show_nulls_as=>' - '
,p_pagination_display_position=>'BOTTOM_RIGHT'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(2689769068667087711)
,p_name=>'P109_SITE'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(10421717133374622829)
,p_prompt=>'Sites'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select d, r from (SELECT a.site_number || '' ('' || FIRST_NAME || '' '' || LAST_NAME || '' - '' || b.invname || '')'' D',
'     , A.STUDY_SITE_ID R, ''1'' s',
'  FROM EDC_STUDY_SITES A,',
'       EDC_SITES B',
' WHERE A.SITE_ID = B.SITE_ID',
'   AND A.STUDY_ID = :APP_EDC_STUDY_ID',
'   AND EDC_AUTH_PKG.CHECK_STUDY_SITE_ACCESS(A.STUDY_SITE_ID) <> 0',
'union',
'select ''All Sites'' D, 999999 r, ''0'' s',
'from dual',
'order by s, d)'))
,p_lov_display_null=>'YES'
,p_lov_null_text=>'--Select--'
,p_cHeight=>1
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_imp.id(11045185769059407896)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'NO'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'SUBMIT'
,p_attribute_03=>'Y'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(2689493361962813876)
,p_name=>'Download PDF_1'
,p_event_sequence=>20
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_imp.id(9405156173309799320)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'click'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(2689493876146813877)
,p_event_id=>wwv_flow_imp.id(2689493361962813876)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'window.open(''../JasperReportsIntegration/report?_repName=SUN_21010_DEV/DICLO_IWRS_SV&_repFormat=csv&_dataSource=default&_outFilename=Subject_Visits.csv&_repLocale=en_US&_repEncoding=UTF-8&P_EDC_ROLE_ID=''+$v("P109_EDC_ROLE_ID_1")+''&P_EDC_USER=''+ $v("P'
||'109_EDC_USER_1") +''&P_EDC_USER_ID=''+ $v("P109_EDC_USER_ID_1")+'''',''_blank'');'
);
wwv_flow_imp.component_end;
end;
/
