prompt --application/pages/page_00040
begin
--   Manifest
--     PAGE: 00040
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>666903967469575309
,p_default_application_id=>10021010
,p_default_id_offset=>759714394172364641
,p_default_owner=>'SUN_21010_DEV'
);
wwv_flow_imp_page.create_page(
 p_id=>40
,p_tab_set=>'TS1'
,p_name=>'Kit Request Detail'
,p_step_title=>'Kit Request Detail'
,p_allow_duplicate_submissions=>'N'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'var htmldb_delete_message=''"DELETE_CONFIRM_MSG"'';',
'',
'function decline_request(){',
'    if(confirm("Are you sure you want to Decline this Shipment Request?")){',
'        reason = $.trim(prompt("Please enter reason for Declining this Shipment Request."));',
'',
'        if(reason){',
'            $(''#P40_DECLINE_REASON_TEMP'').val(reason);',
'            apex.submit(''DECLINE'');',
'        }',
'        else{',
'            alert(''Decline reason is not entered, Please try again'');',
'        }',
'    }',
'}'))
,p_javascript_code_onload=>wwv_flow_string.join(wwv_flow_t_varchar2(
'if($v(''P40_SR_ID'') && ($v(''P40_PM_APPROVED'') == 0 || !$v(''P40_PM_APPROVED''))){',
'    var ajaxRequest = new htmldb_Get(null,  ',
'                                     $x(''pFlowId'').value,',
'                                     ''APPLICATION_PROCESS=SHOW_REASON_FOR_CHANGE'',',
'                                     $x(''pFlowStepId'').value',
'                                    );',
'',
'    var ajaxResult = ajaxRequest.get()',
'',
'    /* Load dynamic JQuery generated by PL/SQL Process*/',
'    //console.log(ajaxResult);',
'    eval(ajaxResult);',
'}'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.reason4change{',
'     display:none;',
'     border-color:red !important;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_help_text=>'No help is available for this page.'
,p_page_component_map=>'02'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(9910398194559419586)
,p_plug_name=>'Kit Request Detail'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(11045180167451407887)
,p_plug_display_sequence=>20
,p_plug_read_only_when_type=>'EXISTS'
,p_plug_read_only_when=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE SR_ID = :P40_SR_ID',
'   AND NVL(REQUEST_STATUS, ''Open'') IN (''Shipped'', ''Cancelled'')'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'TEXT',
  'show_line_breaks', 'Y')).to_clob
,p_plug_comment=>':P40_REQUEST_STATUS= ''Shipped'''
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(9910406178450419600)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(11045179465801407886)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(11045189164405407923)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(11045187162360407898)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(9910406600043419600)
,p_plug_name=>'IP_INVENTORY'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(11045178973639407883)
,p_plug_display_sequence=>10
,p_plug_new_grid_row=>false
,p_list_id=>wwv_flow_imp.id(11051769575586568669)
,p_plug_source_type=>'NATIVE_LIST'
,p_list_template_id=>wwv_flow_imp.id(11045184765473407894)
,p_plug_query_headings_type=>'QUERY_COLUMNS'
,p_plug_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_plug_query_show_nulls_as=>' - '
,p_pagination_display_position=>'BOTTOM_RIGHT'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(9910398627048419588)
,p_button_sequence=>40
,p_button_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_button_name=>'SAVE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(11045186175944407897)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Save'
,p_button_position=>'CHANGE'
,p_button_alignment=>'RIGHT'
,p_button_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE SR_ID = :P40_SR_ID',
'   AND PM_APPROVED IS NULL',
'   and request_status is null'))
,p_button_condition_type=>'EXISTS'
,p_security_scheme=>wwv_flow_imp.id(11045208363860824391)
,p_database_action=>'UPDATE'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(9916207966742603257)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_button_name=>'AUDIT_TRAIL'
,p_button_action=>'DEFINED_BY_DA'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(11045186175944407897)
,p_button_image_alt=>'Audit Trail'
,p_button_position=>'CLOSE'
,p_button_alignment=>'RIGHT'
,p_button_condition=>':P40_SR_ID IS NOT NULL'
,p_button_condition2=>'PLSQL'
,p_button_condition_type=>'EXPRESSION'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(9910399014813419589)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_button_name=>'CANCEL'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(11045186175944407897)
,p_button_image_alt=>'Back'
,p_button_position=>'CLOSE'
,p_button_alignment=>'RIGHT'
,p_button_redirect_url=>'f?p=&APP_ID.:29:&SESSION.::&DEBUG.:::'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(9910399387703419589)
,p_button_sequence=>50
,p_button_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_button_name=>'CREATE'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(11045186175944407897)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Create'
,p_button_position=>'CREATE'
,p_button_alignment=>'RIGHT'
,p_button_condition=>':P40_SR_ID IS NULL'
,p_button_condition2=>'PLSQL'
,p_button_condition_type=>'EXPRESSION'
,p_security_scheme=>wwv_flow_imp.id(11045207987044824391)
,p_database_action=>'INSERT'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(9911229715673911336)
,p_button_sequence=>60
,p_button_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_button_name=>'SEND_2_PM'
,p_button_action=>'REDIRECT_URL'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(11045186175944407897)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Send for Approval'
,p_button_position=>'CREATE'
,p_button_redirect_url=>'javascript:apex.confirm(''Are you sure you want to submit this request, You will not be able to edit this request thereafter.'',''SEND_2_PM'');'
,p_button_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE SR_ID = :P40_SR_ID',
'   AND REQUEST_STATUS IS NULL'))
,p_button_condition_type=>'EXISTS'
,p_security_scheme=>wwv_flow_imp.id(11046584065458172839)
,p_database_action=>'UPDATE'
,p_button_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE SR_ID = :P40_SR_ID',
'   AND REQUEST_STATUS IS NULL',
'',
'',
'',
'Are you sure you want to submit this request for Approval, You will not be able to edit this request thereafter.',
'',
'javascript:apex.confirm(''Are you sure you want to submit this request, You will not be able to edit this request thereafter.'',''SEND_2_PM'');'))
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(9910399856223419590)
,p_button_sequence=>70
,p_button_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_button_name=>'APPROVE'
,p_button_action=>'REDIRECT_URL'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(11045186175944407897)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Approve'
,p_button_position=>'CREATE'
,p_button_redirect_url=>'javascript:apex.confirm(''Are you sure you want to Approve this Shipment Request?'',''APPROVE'');'
,p_button_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE SR_ID = :P40_SR_ID',
'   AND REQUEST_STATUS = ''Open''',
'   AND NVL(PM_APPROVED, 0) = 0'))
,p_button_condition_type=>'EXISTS'
,p_security_scheme=>wwv_flow_imp.id(11062082057979019090)
,p_button_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE SR_ID = :P40_SR_ID',
'   AND REQUEST_STATUS = ''Open''',
'   AND NVL(PM_APPROVED, 0) = 0'))
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(9910400272301419590)
,p_button_sequence=>80
,p_button_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_button_name=>'DECLINE'
,p_button_action=>'REDIRECT_URL'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(11045186175944407897)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Decline'
,p_button_position=>'CREATE'
,p_button_redirect_url=>'javascript:decline_request();'
,p_button_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE SR_ID = :P40_SR_ID',
'   AND REQUEST_STATUS = ''Open''',
'   AND NVL(PM_APPROVED, 0) = 0',
'   AND :APP_EDC_ROLE_ID IN (13, 19/*, 23  Admin, PM, Medical Monitor*/)'))
,p_button_condition_type=>'EXISTS'
,p_security_scheme=>wwv_flow_imp.id(11062082057979019090)
,p_button_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE SR_ID = :P40_SR_ID',
'   AND REQUEST_STATUS = ''Open''',
'   AND NVL(PM_APPROVED, 0) = 0',
'   AND :APP_EDC_ROLE_ID IN (13, 19, 23 /* Admin, PM, Medical Monitor*/)'))
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(9910400600922419591)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_button_name=>'DELETE'
,p_button_action=>'REDIRECT_URL'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(11045186175944407897)
,p_button_image_alt=>'Delete'
,p_button_position=>'DELETE'
,p_button_alignment=>'RIGHT'
,p_button_redirect_url=>'javascript:apex.confirm(htmldb_delete_message,''DELETE'');'
,p_button_execute_validations=>'N'
,p_button_condition_type=>'NEVER'
,p_security_scheme=>wwv_flow_imp.id(11045225087783133792)
,p_database_action=>'DELETE'
);
wwv_flow_imp_page.create_page_branch(
 p_id=>wwv_flow_imp.id(9910414578023419619)
,p_branch_name=>'Go To Page 29'
,p_branch_action=>'f?p=&APP_ID.:40:&SESSION.::&DEBUG.:40:P40_SR_ID:&P40_SR_ID.&success_msg=#SUCCESS_MSG#'
,p_branch_point=>'AFTER_PROCESSING'
,p_branch_type=>'REDIRECT_URL'
,p_branch_sequence=>1
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(750216660873648093)
,p_name=>'P40_EXP_DEL_DATE_CHANGE'
,p_item_sequence=>160
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Kits'
,p_placeholder=>'Reason for change'
,p_display_as=>'NATIVE_TEXTAREA'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_tag_css_classes=>'reason4change'
,p_tag_attributes=>'style="margin-left:15px;"'
,p_begin_on_new_line=>'N'
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_imp.id(11045185664598407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'NVL(:P40_REQUEST_STATUS, ''Open'') = ''Open''',
'AND NVL(:P40_PM_APPROVED, 0) = 0',
'AND :APP_EDC_ROLE_ID IN (13, 19, 23 /* Admin, PM, Medical Monitor*/)'))
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(2009197991288105829)
,p_name=>'P40_QTRY_DEPT'
,p_item_sequence=>240
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_prompt=>'Quantity Of Depot'
,p_source=>'P40_STUDY_SITE_ID'
,p_source_type=>'ITEM'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>12
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_imp.id(11045185769059407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'Y'
,p_attribute_03=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(7187315333503234193)
,p_name=>'P40_STUDY_SITE_ID_CHANGE'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Kits'
,p_placeholder=>'Reason for change'
,p_display_as=>'NATIVE_TEXTAREA'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_tag_css_classes=>'reason4change'
,p_tag_attributes=>'style="margin-left:15px;"'
,p_begin_on_new_line=>'N'
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_imp.id(11045185664598407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'(NVL(:P40_PM_APPROVED, 0) <> 0',
' AND :APP_EDC_ROLE_ID NOT IN (13, 19, 23)',
')'))
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(7187315419046234194)
,p_name=>'P40_SR_REQ_DATE_CHANGE'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Kits'
,p_placeholder=>'Reason for change'
,p_display_as=>'NATIVE_TEXTAREA'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_tag_css_classes=>'reason4change'
,p_tag_attributes=>'style="margin-left:15px;"'
,p_begin_on_new_line=>'N'
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_imp.id(11045185664598407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'NVL(:P40_REQUEST_STATUS, ''Open'') = ''Open''',
'AND NVL(:P40_PM_APPROVED, 0) = 0',
'AND :APP_EDC_ROLE_ID IN (13, 19, 23 /* Admin, PM, Medical Monitor*/)'))
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9521366254546728010)
,p_name=>'P40_RESCUE_MEDICINE'
,p_item_sequence=>120
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Total Number of Kits'
,p_source=>'RESCUE_MEDICINE'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_NUMBER_FIELD'
,p_cSize=>12
,p_tag_attributes=>'READONLY'
,p_label_alignment=>'RIGHT'
,p_read_only_when=>':P40_REQUEST_STATUS IS NOT NULL'
,p_read_only_when2=>'PLSQL'
,p_read_only_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185979045407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_03=>'right'
,p_attribute_04=>'text'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'',
''))
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9521366407555728011)
,p_name=>'P40_RESCUE_MEDICINE_CHANGE'
,p_item_sequence=>130
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Placebo Quantity'
,p_placeholder=>'Reason for change'
,p_display_as=>'NATIVE_TEXTAREA'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_tag_css_classes=>'reason4change'
,p_tag_attributes=>'style="margin-left:15px;"'
,p_begin_on_new_line=>'N'
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_display_when=>wwv_flow_string.join(wwv_flow_t_varchar2(
'--NVL(:P40_REQUEST_STATUS, ''Open'') = ''Open''',
':P40_REQUEST_STATUS IS NULL AND NVL(:P40_PM_APPROVED, 0) = 0'))
,p_display_when2=>'PLSQL'
,p_display_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185664598407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'(NVL(:P40_PM_APPROVED, 0) <> 0',
' AND :APP_EDC_ROLE_ID NOT IN (13, 19, 23)',
')',
'',
'NVL(:P40_REQUEST_STATUS, ''Open'') = ''Open''',
'AND NVL(:P40_PM_APPROVED, 0) = 0',
''))
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910401004801419592)
,p_name=>'P40_SR_ID'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Sr Id'
,p_source=>'SR_ID'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_imp.id(11045185769059407896)
,p_item_template_options=>'#DEFAULT#'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910401418295419592)
,p_name=>'P40_IP_REQ_ID'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Kit Request #'
,p_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT LPAD(:P40_SR_ID, 3, ''0'')',
'  FROM DUAL'))
,p_source_type=>'QUERY'
,p_display_as=>'NATIVE_DISPLAY_ONLY'
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_imp.id(11045185769059407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'VALUE'
,p_attribute_04=>'Y'
,p_attribute_05=>'PLAIN'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910401838010419593)
,p_name=>'P40_STUDY_SITE_ID'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Site'
,p_source=>'STUDY_SITE_ID'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT a.site_number || '' ('' || FIRST_NAME || '' '' || LAST_NAME || '' - '' || b.invname || '')'' D,',
'       A.STUDY_SITE_ID R ',
'  FROM EDC_STUDY_SITES A,',
'       EDC_SITES B',
' WHERE A.SITE_ID = B.SITE_ID',
'   AND A.STUDY_ID = :APP_EDC_STUDY_ID',
'   AND EDC_AUTH_PKG.CHECK_STUDY_SITE_ACCESS(A.STUDY_SITE_ID) <> 0',
' ORDER BY 1'))
,p_lov_display_null=>'YES'
,p_lov_null_text=>'-- Select Site --'
,p_cHeight=>1
,p_label_alignment=>'RIGHT'
,p_read_only_when=>':P40_REQUEST_STATUS IS NOT NULL'
,p_read_only_when2=>'PLSQL'
,p_read_only_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185979045407896)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
':P40_SR_ID IS NOT NULL',
'-------------',
'SELECT '' Site : '' || A.SITE_NUMBER || '' ( '' || B.INVNAME || '' )'' D,',
'       A.STUDY_SITE_ID R ',
'  FROM EDC_STUDY_SITES A,',
'       EDC_SITES B',
' WHERE A.SITE_ID = B.SITE_ID',
'   AND A.STUDY_ID = :APP_EDC_STUDY_ID',
'   AND (:APP_EDC_USER = A.USER_ID',
'        OR',
'        :APP_EDC_ROLE_ID IN (13, 18) -- Admin, DM',
'        OR',
'        A.STUDY_SITE_ID IN (SELECT STUDY_SITE_ID',
'                              FROM EDC_IP_SHIPMENT_REQ',
'                             WHERE SR_ID = :P40_SR_ID',
'                           )',
'       )',
' ORDER BY 1'))
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910402194619419593)
,p_name=>'P40_SR_REQ_DATE'
,p_is_required=>true
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_item_default=>'to_Date(to_char(localtimestamp,''DD-MON-YYYY''),''DD-MON-YYYY'')'
,p_item_default_type=>'EXPRESSION'
,p_item_default_language=>'PLSQL'
,p_prompt=>'Request Date'
,p_source=>'SR_REQ_DATE'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>12
,p_cMaxlength=>255
,p_tag_attributes=>'readonly="readonly"'
,p_label_alignment=>'RIGHT'
,p_read_only_when=>':P40_REQUEST_STATUS IS NOT NULL'
,p_read_only_when2=>'PLSQL'
,p_read_only_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185979045407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910402606166419594)
,p_name=>'P40_KITS'
,p_item_sequence=>80
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'No of Test Kits'
,p_source=>'KITS'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_NUMBER_FIELD'
,p_cSize=>12
,p_cMaxlength=>3
,p_label_alignment=>'RIGHT'
,p_read_only_when=>':P40_REQUEST_STATUS IS NOT NULL'
,p_read_only_when2=>'PLSQL'
,p_read_only_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185979045407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_03=>'right'
,p_attribute_04=>'text'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910402988553419595)
,p_name=>'P40_PLACIBO_RUNIN'
,p_item_sequence=>100
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_source=>'PLACIBO_RUNIN'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910403397987419595)
,p_name=>'P40_MIN_DATE'
,p_item_sequence=>140
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_source=>'+0d'
,p_source_type=>'STATIC'
,p_display_as=>'NATIVE_HIDDEN'
,p_display_when=>':P40_SR_ID IS NULL'
,p_display_when2=>'PLSQL'
,p_display_when_type=>'EXPRESSION'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910403844513419596)
,p_name=>'P40_EXP_DEL_DATE'
,p_item_sequence=>150
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Expected Delivery Date'
,p_source=>'EXP_DEL_DATE'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_DATE_PICKER'
,p_cSize=>12
,p_cMaxlength=>255
,p_tag_attributes=>'readonly="readonly"'
,p_label_alignment=>'RIGHT'
,p_read_only_when=>':P40_REQUEST_STATUS IS NOT NULL'
,p_read_only_when2=>'PLSQL'
,p_read_only_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185769059407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_02=>'&P40_SR_REQ_DATE.'
,p_attribute_04=>'button'
,p_attribute_05=>'N'
,p_attribute_07=>'NONE'
,p_item_comment=>':P40_SR_ID IS NOT NULL'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910404198130419596)
,p_name=>'P40_PM_APPROVED'
,p_item_sequence=>170
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_source=>'PM_APPROVED'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910404671438419597)
,p_name=>'P40_REQUEST_STATUS'
,p_item_sequence=>180
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_item_default=>'Open'
,p_prompt=>'Request Status'
,p_source=>'REQUEST_STATUS'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>'STATIC:Open;Open,Shipped;Shipped,Cancelled;Cancelled'
,p_cHeight=>1
,p_label_alignment=>'RIGHT'
,p_display_when=>':P40_SR_ID IS NOT NULL AND NVL(:P40_PM_APPROVED, ''0'') = ''1'''
,p_display_when2=>'PLSQL'
,p_display_when_type=>'EXPRESSION'
,p_read_only_when=>':APP_EDC_ROLE_ID NOT IN (13 /* Admin, DM*/)'
,p_read_only_when2=>'PLSQL'
,p_read_only_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185857341407896)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910405000095419598)
,p_name=>'P40_SHIPMENT_NO'
,p_item_sequence=>210
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Shipment No.'
,p_source=>'SHIPMENT_NO'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT SHIP_NO D,',
'       SHIP_ID R',
'  FROM EDC_IP_SHIPMENT',
' WHERE STUDY_SITE_ID = :P40_STUDY_SITE_ID',
'   AND SHIP_STATUS IN (''Dispatched'', ''Delivered'')',
'   AND SHIP_ID NOT IN(SELECT SHIPMENT_NO',
'                        FROM EDC_IP_SHIPMENT_REQ',
'                       WHERE SHIPMENT_NO IS NOT NULL',
'                     )',
'UNION',
'SELECT SHIP_NO D,',
'       SHIP_ID R',
'  FROM EDC_IP_SHIPMENT',
' WHERE SHIP_ID IN(SELECT SHIPMENT_NO',
'                    FROM EDC_IP_SHIPMENT_REQ',
'                   WHERE SR_ID = :P40_SR_ID',
'                 )',
''))
,p_lov_display_null=>'YES'
,p_lov_null_text=>'-- Select --'
,p_cHeight=>1
,p_label_alignment=>'RIGHT'
,p_display_when=>':P40_SR_ID IS NOT NULL AND NVL(:P40_PM_APPROVED, ''0'') = ''1'''
,p_display_when2=>'PLSQL'
,p_display_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185979045407896)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'NO'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Post Test:',
'<span id="shipment_note"> Note : Shipments <u>Dispatched</u> to site can be selected</span>'))
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910405445113419599)
,p_name=>'P40_RESPONSE_BY'
,p_item_sequence=>220
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_item_default=>':APP_USER_NAME'
,p_item_default_type=>'EXPRESSION'
,p_item_default_language=>'PLSQL'
,p_source=>'RESPONSE_BY'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_display_when=>':P40_SR_ID IS NOT NULL'
,p_display_when2=>'PLSQL'
,p_display_when_type=>'EXPRESSION'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9910405792010419599)
,p_name=>'P40_RESPONSE_DATE'
,p_item_sequence=>230
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_item_default=>'LOCALTIMESTAMP'
,p_item_default_type=>'EXPRESSION'
,p_item_default_language=>'PLSQL'
,p_source=>'RESPONSE_DATE'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_HIDDEN'
,p_display_when=>':P40_SR_ID IS NOT NULL'
,p_display_when2=>'PLSQL'
,p_display_when_type=>'EXPRESSION'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9911229793573911337)
,p_name=>'P40_DECLINE_REASON_TEMP'
,p_item_sequence=>200
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9911229973221911338)
,p_name=>'P40_DECLINE_REASON'
,p_item_sequence=>190
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Declining Reason'
,p_source=>'DECLINE_REASON'
,p_source_type=>'DB_COLUMN'
,p_display_as=>'NATIVE_DISPLAY_ONLY'
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_display_when=>':P40_DECLINE_REASON IS NOT NULL'
,p_display_when2=>'PLSQL'
,p_display_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185769059407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'VALUE'
,p_attribute_04=>'Y'
,p_attribute_05=>'PLAIN'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9911230063096911339)
,p_name=>'P40_KITS_CHANGE'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Kits'
,p_placeholder=>'Reason for change'
,p_display_as=>'NATIVE_TEXTAREA'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_tag_css_classes=>'reason4change'
,p_tag_attributes=>'style="margin-left:15px;"'
,p_begin_on_new_line=>'N'
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_display_when=>wwv_flow_string.join(wwv_flow_t_varchar2(
'NVL(:P40_REQUEST_STATUS, ''Open'') = ''Open''',
'AND NVL(:P40_PM_APPROVED, 0) = 0',
''))
,p_display_when2=>'PLSQL'
,p_display_when_type=>'EXPRESSION'
,p_field_template=>wwv_flow_imp.id(11045185664598407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'(NVL(:P40_PM_APPROVED, 0) <> 0',
' AND :APP_EDC_ROLE_ID NOT IN (13, 19, 23)',
')'))
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(9911230489836911344)
,p_name=>'P40_PLACIBO_RUNIN_CHANGE'
,p_item_sequence=>110
,p_item_plug_id=>wwv_flow_imp.id(9910398194559419586)
,p_use_cache_before_default=>'NO'
,p_prompt=>'Placebo Run-in'
,p_placeholder=>'Reason for change'
,p_display_as=>'NATIVE_TEXTAREA'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_tag_css_classes=>'reason4change'
,p_tag_attributes=>'style="margin-left:15px;"'
,p_begin_on_new_line=>'N'
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_display_when_type=>'NEVER'
,p_field_template=>wwv_flow_imp.id(11045185664598407896)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_item_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'(NVL(:P40_PM_APPROVED, 0) <> 0',
' AND :APP_EDC_ROLE_ID NOT IN (13, 19, 23)',
')',
'',
'',
'',
'NVL(:P40_REQUEST_STATUS, ''Open'') = ''Open''',
'AND NVL(:P40_PM_APPROVED, 0) = 0'))
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(9910407767396419610)
,p_validation_name=>'P40_RESPONSE_DATE must be timestamp'
,p_validation_sequence=>140
,p_validation=>'P40_RESPONSE_DATE'
,p_validation_type=>'ITEM_IS_TIMESTAMP'
,p_error_message=>'#LABEL# must be a valid timestamp.'
,p_associated_item=>wwv_flow_imp.id(9910405792010419599)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(9910408167822419610)
,p_validation_name=>'P40_SHIPMENT_NO IS NOT NULL WHEN Request Status IS "Shipped"'
,p_validation_sequence=>150
,p_validation=>'P40_SHIPMENT_NO'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Shipment No. must have some value.'
,p_validation_condition=>':P40_REQUEST_STATUS=''Shipped'''
,p_validation_condition2=>'PLSQL'
,p_validation_condition_type=>'EXPRESSION'
,p_associated_item=>wwv_flow_imp.id(9910405000095419598)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(9910408522851419611)
,p_validation_name=>'P40_STUDY_SITE_ID must be Active'
,p_validation_sequence=>160
,p_validation=>'EDC_UTIL.GET_SITE_STATUS(:P40_STUDY_SITE_ID) = 3'
,p_validation2=>'PLSQL'
,p_validation_type=>'EXPRESSION'
,p_error_message=>'IP Request is disable because this site is not Active'
,p_validation_condition=>':REQUEST IN (''CREATE'') AND :P40_STUDY_SITE_ID IS NOT NULL'
,p_validation_condition2=>'PLSQL'
,p_validation_condition_type=>'EXPRESSION'
,p_associated_item=>wwv_flow_imp.id(9910401838010419593)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(9911228021514911319)
,p_validation_name=>'Quantity > 0'
,p_validation_sequence=>170
,p_validation=>'NVL(TRIM(:P40_KITS), 0) + NVL(TRIM(:P40_PLACIBO_RUNIN), 0) + NVL(TRIM(:P40_RESCUE_MEDICINE), 0) > 0'
,p_validation2=>'PLSQL'
,p_validation_type=>'EXPRESSION'
,p_error_message=>'Kit & Placebo Run-in & Rescue Medicine can not be 0'
,p_validation_condition_type=>'NEVER'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_validation_comment=>'NVL(TRIM(:P40_KITS), 0) + NVL(TRIM(:P40_PLACIBO_RUNIN), 0) + NVL(TRIM(:P40_RESCUE_MEDICINE), 0) > 0'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(9916321113967416306)
,p_validation_name=>'P40_KITS_CHANGE'
,p_validation_sequence=>180
,p_validation=>'P40_KITS_CHANGE'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Reason for change must be entered for <b>Test Kits</b>'
,p_validation_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(KITS, 0) <> NVL(:P40_KITS, 0)',
'   AND TRIM(:P40_KITS_CHANGE) IS NULL',
'   AND SR_ID = :P40_SR_ID',
'   --AND REQUEST_STATUS = ''Open''',
'   AND NVL(:P40_PM_APPROVED, 0) = 0'))
,p_validation_condition_type=>'EXISTS'
,p_associated_item=>wwv_flow_imp.id(9911230063096911339)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(776936191154599657)
,p_validation_name=>'P40_PLACIBO_RUNIN_CHANGE'
,p_validation_sequence=>190
,p_validation=>'P40_PLACIBO_RUNIN_CHANGE'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Reason for change must be entered for <b>Placebo Kits</b>'
,p_validation_condition_type=>'NEVER'
,p_associated_item=>wwv_flow_imp.id(9911230489836911344)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_validation_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(PLACIBO_RUNIN, 0) <> NVL(:P40_PLACIBO_RUNIN, 0)',
'   AND TRIM(:P40_PLACIBO_RUNIN_CHANGE) IS NULL',
'   AND SR_ID = :P40_SR_ID',
'   --AND REQUEST_STATUS = ''Open''',
'   AND NVL(:P40_PM_APPROVED, 0) = 0'))
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(7187315676606234197)
,p_validation_name=>'P40_STUDY_SITE_CHANGE'
,p_validation_sequence=>200
,p_validation=>'P40_STUDY_SITE_ID_CHANGE'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Reason for change must be entered for <b>Sites</b>'
,p_validation_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(STUDY_SITE_ID, 0) <> NVL(:P40_STUDY_SITE_ID, 0)',
'   AND TRIM(:P40_STUDY_SITE_ID_CHANGE) IS NULL',
'   AND SR_ID = :P40_SR_ID',
'   --AND REQUEST_STATUS = ''Open''',
'   AND NVL(:P40_PM_APPROVED, 0) = 0'))
,p_validation_condition_type=>'EXISTS'
,p_associated_item=>wwv_flow_imp.id(7187315333503234193)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(7187315802907234198)
,p_validation_name=>'P40_REQUEST_DATE_CHANGE'
,p_validation_sequence=>210
,p_validation=>'P40_SR_REQ_DATE_CHANGE'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Reason for change must be entered for <b>Request Date</b>'
,p_validation_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(SR_REQ_DATE, TO_DATE(''01-jan-2000'')) <> NVL(:P40_SR_REQ_DATE, TO_DATE(''01-jan-2000''))',
'   AND TRIM(:P40_SR_REQ_DATE_CHANGE) IS NULL',
'   AND SR_ID = :P40_SR_ID',
'   --AND REQUEST_STATUS = ''Open''',
'   AND NVL(:P40_PM_APPROVED, 0) = 0'))
,p_validation_condition_type=>'EXISTS'
,p_associated_item=>wwv_flow_imp.id(7187315419046234194)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(750216696943648094)
,p_validation_name=>'P40_EXP_DEL_DATE_CHANGE'
,p_validation_sequence=>220
,p_validation=>'P40_EXP_DEL_DATE_CHANGE'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Reason for change must be entered for <b>Expected Delivery Date</b>'
,p_validation_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(EXP_DEL_DATE, TO_DATE(''01-jan-2000'')) <> NVL(:P40_EXP_DEL_DATE, TO_DATE(''01-jan-2000''))',
'   AND TRIM(:P40_EXP_DEL_DATE_CHANGE) IS NULL',
'   AND SR_ID = :P40_SR_ID',
'   --AND REQUEST_STATUS = ''Open''',
'   AND NVL(:P40_PM_APPROVED, 0) = 0'))
,p_validation_condition_type=>'EXISTS'
,p_associated_item=>wwv_flow_imp.id(750216660873648093)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(7187315521410234195)
,p_validation_name=>'P40_REQ_DATE_CHANGE'
,p_validation_sequence=>230
,p_validation=>'P40_SR_REQ_DATE_CHANGE'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Reason for change must be entered for <b>Request Date</b>'
,p_validation_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(SR_REQ_DATE, TO_CHAR(''01-jan-2000'')) <> NVL(:P40_SR_REQ_DATE, TO_CHAR(''01-jan-2000''))',
'   AND TRIM(:P40_SR_REQ_DATE_CHANGE) IS NULL',
'   AND SR_ID = :P40_SR_ID',
'   AND REQUEST_STATUS = ''Open''',
'   AND NVL(:P40_PM_APPROVED, 0) = 0'))
,p_validation_condition_type=>'EXISTS'
,p_associated_item=>wwv_flow_imp.id(7187315419046234194)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(7187315650973234196)
,p_validation_name=>'P40_SITE_CHANGE'
,p_validation_sequence=>240
,p_validation=>'P40_STUDY_SITE_ID_CHANGE'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Reason for change must be entered for <b>Site</b>'
,p_validation_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(KITS, 0) <> NVL(:P40_KITS, 0)',
'   AND TRIM(:P40_KITS_CHANGE) IS NULL',
'   AND SR_ID = :P40_SR_ID',
'   AND REQUEST_STATUS = ''Open''',
'   AND NVL(:P40_PM_APPROVED, 0) = 0'))
,p_validation_condition_type=>'EXISTS'
,p_associated_item=>wwv_flow_imp.id(7187315333503234193)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(9521367067147728018)
,p_validation_name=>'P40_RESCUE_MEDICINE_CHANGE'
,p_validation_sequence=>250
,p_validation=>'P40_RESCUE_MEDICINE_CHANGE'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Reason for change must be entered for <b>Total Number of Kits</b>'
,p_validation_condition=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(RESCUE_MEDICINE, 0) <> NVL(:P40_RESCUE_MEDICINE, 0)',
'   AND TRIM(:P40_RESCUE_MEDICINE_CHANGE) IS NULL',
'   AND SR_ID = :P40_SR_ID',
'   --AND REQUEST_STATUS = ''Open''',
'   AND NVL(:P40_PM_APPROVED, 0) = 0'))
,p_validation_condition_type=>'EXISTS'
,p_associated_item=>wwv_flow_imp.id(9521366407555728011)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_validation_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  V_RESCUE_MEDICINE VARCHAR2(200);',
'BEGIN',
'  IF :P40_SR_ID IS NULL THEN',
'    RETURN FALSE;',
'  ELSE',
'    SELECT RESCUE_MEDICINE',
'      INTO V_RESCUE_MEDICINE',
'      FROM EDC_IP_SHIPMENT_REQ',
'     WHERE SR_ID = :P40_SR_ID;',
'',
'    IF V_RESCUE_MEDICINE != :P40_RESCUE_MEDICINE THEN',
'      RETURN TRUE;',
'    ELSIF V_RESCUE_MEDICINE IS NULL AND :P40_RESCUE_MEDICINE IS NOT NULL THEN',
'      RETURN TRUE;',
'    ELSIF V_RESCUE_MEDICINE IS NOT NULL AND :P40_RESCUE_MEDICINE IS NULL THEN',
'      RETURN TRUE;',
'    ELSE',
'      RETURN FALSE;',
'    END IF;',
'  END IF;',
'END;'))
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(9540825924729801936)
,p_validation_name=>'P40_RESCUE_MEDICINE multiply * 2'
,p_validation_sequence=>260
,p_validation=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'V_VAL NUMBER;',
'BEGIN',
'    V_VAL  := MOD(:P40_RESCUE_MEDICINE, 2);',
' ',
' IF :P40_RESCUE_MEDICINE = 0 THEN',
'     RETURN FALSE;',
' ELSE',
'        IF V_VAL = 0 THEN',
'           RETURN TRUE; ',
'        ELSE',
'          RETURN FALSE;',
'        END IF;  ',
'  END IF;  ',
'END;'))
,p_validation2=>'PLSQL'
,p_validation_type=>'FUNC_BODY_RETURNING_BOOLEAN'
,p_error_message=>'Total No. of kits must be in multiplication of 2'
,p_validation_condition_type=>'NEVER'
,p_associated_item=>wwv_flow_imp.id(9521366254546728010)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(776936108065599656)
,p_validation_name=>'P40_RESCUE_MEDICINE_NN'
,p_validation_sequence=>270
,p_validation=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'V_ID NUMBER;',
'BEGIN',
'    SELECT INSTR(TO_CHAR(:P40_RESCUE_MEDICINE),''.'') AS VAL INTO V_ID FROM DUAL;',
'    IF :P40_RESCUE_MEDICINE IS NULL THEN ',
'        RETURN ''Total Number of Kits Kits must have some values'';',
'    ELSIF TO_NUMBER(:P40_RESCUE_MEDICINE) <= 0 THEN ',
'        RETURN ''Total Number of Kits Kits must be greater than 0'';',
'    ELSIF TO_NUMBER(V_ID) > 0 THEN ',
'        RETURN ''Total Number of Kits enter the non decimal value'';',
'    END IF;',
'EXCEPTION WHEN OTHERS THEN RETURN NULL;',
'END;'))
,p_validation2=>'PLSQL'
,p_validation_type=>'FUNC_BODY_RETURNING_ERR_TEXT'
,p_associated_item=>wwv_flow_imp.id(9521366254546728010)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(9540196905280884695)
,p_validation_name=>'Kits - divisible by 4'
,p_validation_sequence=>280
,p_validation=>'MOD(:P40_KITS, 4) = 0'
,p_validation2=>'PLSQL'
,p_validation_type=>'EXPRESSION'
,p_error_message=>'Kits must be in multiplication of 4.'
,p_validation_condition_type=>'NEVER'
,p_associated_item=>wwv_flow_imp.id(9910402606166419594)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(8840623186902622688)
,p_validation_name=>'P40_KITS > 0'
,p_validation_sequence=>290
,p_validation=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'V_ID NUMBER;',
'BEGIN',
'    SELECT INSTR(TO_CHAR(:P40_KITS),''.'') AS VAL INTO V_ID FROM DUAL;',
'    IF :P40_KITS IS NULL THEN ',
'        RETURN ''Test Kits must have some values'';',
'    ELSIF TO_NUMBER(:P40_KITS) <= 0 THEN ',
'        RETURN ''Test Kits must be greater than 0'';',
'    ELSIF TO_NUMBER(V_ID) > 0 THEN ',
'        RETURN ''Please enter the non decimal value'';',
'    END IF;',
'EXCEPTION WHEN OTHERS THEN RETURN NULL;',
'END;'))
,p_validation2=>'PLSQL'
,p_validation_type=>'FUNC_BODY_RETURNING_ERR_TEXT'
,p_associated_item=>wwv_flow_imp.id(9910402606166419594)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(776935792346599653)
,p_validation_name=>'P40_PLACIBO_RUNIN  > 0'
,p_validation_sequence=>300
,p_validation=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'V_ID NUMBER;',
'BEGIN',
'    SELECT INSTR(TO_CHAR(:P40_PLACIBO_RUNIN),''.'') AS VAL INTO V_ID FROM DUAL;',
'    IF :P40_PLACIBO_RUNIN IS NULL THEN ',
'        RETURN ''Placebo Kits must have some values'';',
'    ELSIF TO_NUMBER(:P40_PLACIBO_RUNIN) <= 0 THEN ',
'        RETURN ''Placebo Kits must be greater than 0'';',
'    ELSIF TO_NUMBER(V_ID) > 0 THEN ',
'        RETURN ''Please enter the non decimal value'';',
'    END IF;',
'EXCEPTION WHEN OTHERS THEN RETURN NULL;',
'END;'))
,p_validation2=>'PLSQL'
,p_validation_type=>'FUNC_BODY_RETURNING_ERR_TEXT'
,p_validation_condition_type=>'NEVER'
,p_associated_item=>wwv_flow_imp.id(9910402988553419595)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(2009581632766490790)
,p_validation_name=>'DEPOT_KIT_NOT_NULL'
,p_validation_sequence=>310
,p_validation=>':P40_QTRY_DEPT<> 0'
,p_validation2=>'PLSQL'
,p_validation_type=>'EXPRESSION'
,p_error_message=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Depot Does Not Have A KITS',
''))
,p_validation_condition=>':REQUEST IN (''CREATE'') AND :P40_STUDY_SITE_ID IS NOT NULL'
,p_validation_condition2=>'PLSQL'
,p_validation_condition_type=>'EXPRESSION'
,p_associated_item=>wwv_flow_imp.id(2009197991288105829)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(1190697413477661924)
,p_validation_name=>'P40_STUDY_SITE_ID_NN'
,p_validation_sequence=>320
,p_validation=>'P40_STUDY_SITE_ID'
,p_validation_type=>'ITEM_NOT_NULL'
,p_error_message=>'Site must have some value.'
,p_associated_item=>wwv_flow_imp.id(9910401838010419593)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(750216157058648088)
,p_validation_name=>'Validation for kits'
,p_validation_sequence=>330
,p_validation=>wwv_flow_string.join(wwv_flow_t_varchar2(
'IF (:P40_KITS <> :P40_PLACIBO_RUNIN) THEN',
'    RETURN ''No of Test Kits must have same value as No of Placebo Kits.'';',
'END IF;'))
,p_validation2=>'PLSQL'
,p_validation_type=>'FUNC_BODY_RETURNING_ERR_TEXT'
,p_validation_condition_type=>'NEVER'
,p_associated_item=>wwv_flow_imp.id(9910402606166419594)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(750216250441648089)
,p_validation_name=>'Validation for placa'
,p_validation_sequence=>340
,p_validation=>wwv_flow_string.join(wwv_flow_t_varchar2(
'IF (:P40_KITS <> :P40_PLACIBO_RUNIN) THEN',
'    RETURN ''No of Placebo Kits must have same value as No of Test Kits.'';',
'END IF;'))
,p_validation2=>'PLSQL'
,p_validation_type=>'FUNC_BODY_RETURNING_ERR_TEXT'
,p_validation_condition_type=>'NEVER'
,p_associated_item=>wwv_flow_imp.id(9910402988553419595)
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_imp_page.create_page_validation(
 p_id=>wwv_flow_imp.id(628363860632369645)
,p_validation_name=>'Insufficient Total Qty Validation'
,p_validation_sequence=>350
,p_validation=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'V_CNT NUMBER;',
'BEGIN',
'IF :P40_RESCUE_MEDICINE IS NOT NULL THEN ',
'SELECT COUNT(8) INTO V_CNT FROM EDC_IP_DETAIL',
'WHERE NVL(IP_STATUS,1)=1;',
'IF V_CNT=0 THEN ',
'RETURN ''Depot Does not have quantity at depot'';',
'ELSIF :P40_RESCUE_MEDICINE>V_CNT THEN',
'RETURN ''Required Quantity not available at depot'';',
'END IF;',
'END IF;',
'end ;'))
,p_validation2=>'PLSQL'
,p_validation_type=>'FUNC_BODY_RETURNING_ERR_TEXT'
,p_always_execute=>'Y'
,p_associated_item=>wwv_flow_imp.id(9521366254546728010)
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(9910411591857419615)
,p_name=>'Show/Hide Shipment # - on Request Status change'
,p_event_sequence=>10
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P40_REQUEST_STATUS'
,p_condition_element=>'P40_REQUEST_STATUS'
,p_triggering_condition_type=>'EQUALS'
,p_triggering_expression=>'Shipped'
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'change'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9910412077845419615)
,p_event_id=>wwv_flow_imp.id(9910411591857419615)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P40_SHIPMENT_NO'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9910412654576419616)
,p_event_id=>wwv_flow_imp.id(9910411591857419615)
,p_event_result=>'FALSE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_CLEAR'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P40_SHIPMENT_NO'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9910413155316419617)
,p_event_id=>wwv_flow_imp.id(9910411591857419615)
,p_event_result=>'FALSE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P40_SHIPMENT_NO'
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9910413585258419617)
,p_event_id=>wwv_flow_imp.id(9910411591857419615)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#shipment_note'').show();'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9910414122610419618)
,p_event_id=>wwv_flow_imp.id(9910411591857419615)
,p_event_result=>'FALSE'
,p_action_sequence=>30
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#shipment_note'').hide();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(9916208326857604932)
,p_name=>'Open Audit Trail Popup (Page 41)'
,p_event_sequence=>20
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_imp.id(9916207966742603257)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'click'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9916208715641604936)
,p_event_id=>wwv_flow_imp.id(9916208326857604932)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'PLUGIN_COM_SKILLBUILDERS_MODAL_PAGE'
,p_attribute_01=>'Audit Trail'
,p_attribute_02=>'STATIC'
,p_attribute_03=>'f?p=&APP_ID.:41:&APP_SESSION.:::41:P41_PAGE_ID,P41_PK_ID,P41_TABLE_NAME:&APP_PAGE_ID.,&P40_SR_ID.,EDC_IP_SHIPMENT_REQ'
,p_attribute_06=>'div#success-message'
,p_attribute_07=>'STATIC_%'
,p_attribute_08=>'70'
,p_attribute_09=>'80'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(9911230328494911342)
,p_name=>'Show/Hide ''Reason for change'' fields'
,p_event_sequence=>30
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'EXPRESSION'
,p_display_when_cond=>wwv_flow_string.join(wwv_flow_t_varchar2(
':P40_REQUEST_STATUS = ''Open''',
'AND NVL(:P40_PM_APPROVED, 0) = 0',
''))
,p_display_when_cond2=>'PLSQL'
,p_da_event_comment=>':P1001_DM_ID IS NOT NULL'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9911230408147911343)
,p_event_id=>wwv_flow_imp.id(9911230328494911342)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  var ajaxRequest = new htmldb_Get( ',
'                                  null,  ',
'                                  $x(''pFlowId'').value,',
'                                  ''APPLICATION_PROCESS=SHOW_REASON_FOR_CHANGE'',',
'                                  $x(''pFlowStepId'').value',
'                                  );',
'',
'  var ajaxResult = ajaxRequest.get()',
'',
'  /* Load dynamic JQuery generated by PL/SQL Process*/',
'  //console.log(ajaxResult);',
'  eval(ajaxResult);'))
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(9916320203541414532)
,p_name=>'Show P40_KITS'
,p_event_sequence=>40
,p_bind_type=>'live'
,p_bind_delegate_to_selector=>'.uMessageRegion'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'EXISTS'
,p_display_when_cond=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(KITS, -1) <> :P40_KITS',
'   AND SR_ID = :P40_SR_ID'))
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9916320638247414538)
,p_event_id=>wwv_flow_imp.id(9916320203541414532)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#P40_KITS_CHANGE'').show();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(7187315885306234199)
,p_name=>'Show P40_STUDY_SITE_ID'
,p_event_sequence=>50
,p_bind_type=>'live'
,p_bind_delegate_to_selector=>'.uMessageRegion'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'EXISTS'
,p_display_when_cond=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(STUDY_SITE_ID, -1) <> :P40_STUDY_SITE_ID',
'   AND SR_ID = :P40_SR_ID'))
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(7187316006148234200)
,p_event_id=>wwv_flow_imp.id(7187315885306234199)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#P40_STUDY_SITE_ID_CHANGE'').show();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(7187316135934234201)
,p_name=>'Show P40_SR_REQ_DATE_CHANGE'
,p_event_sequence=>60
,p_bind_type=>'live'
,p_bind_delegate_to_selector=>'.uMessageRegion'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'EXISTS'
,p_display_when_cond=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(SR_REQ_DATE, TO_DATE(''01-JAN-2000'')) <> :P40_SR_REQ_DATE',
'   AND SR_ID = :P40_SR_ID'))
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(7187316213899234202)
,p_event_id=>wwv_flow_imp.id(7187316135934234201)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#P40_SR_REQ_DATE_CHANGE'').show();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(750216833331648095)
,p_name=>'Show P40_EXP_DEL_DATE_CHANGE'
,p_event_sequence=>70
,p_bind_type=>'live'
,p_bind_delegate_to_selector=>'.uMessageRegion'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'EXISTS'
,p_display_when_cond=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(EXP_DEL_DATE, TO_DATE(''01-JAN-2000'')) <> :P40_EXP_DEL_DATE',
'   AND SR_ID = :P40_SR_ID'))
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(750216907238648096)
,p_event_id=>wwv_flow_imp.id(750216833331648095)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#P40_EXP_DEL_DATE_CHANGE'').show();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(9916321312658466596)
,p_name=>'Show P40_PLACIBO_RUNIN'
,p_event_sequence=>80
,p_bind_type=>'live'
,p_bind_delegate_to_selector=>'.uMessageRegion'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'NEVER'
,p_da_event_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(PLACIBO_RUNIN, -1) <> :P40_PLACIBO_RUNIN',
'   AND SR_ID = :P40_SR_ID'))
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9916321459513466597)
,p_event_id=>wwv_flow_imp.id(9916321312658466596)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#P40_PLACIBO_RUNIN_CHANGE'').show();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(9521366643177728014)
,p_name=>'Show P40_RESCUE_MEDICINE'
,p_event_sequence=>90
,p_bind_type=>'live'
,p_bind_delegate_to_selector=>'.uMessageRegion'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'EXISTS'
,p_display_when_cond=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(RESCUE_MEDICINE, -1) <> :P40_RESCUE_MEDICINE',
'   AND SR_ID = :P40_SR_ID'))
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9521366765419728015)
,p_event_id=>wwv_flow_imp.id(9521366643177728014)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#P40_RESCUE_MEDICINE_CHANGE'').show();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(9521366893445728016)
,p_name=>'Show P40_ARM_4_QTY'
,p_event_sequence=>100
,p_bind_type=>'live'
,p_bind_delegate_to_selector=>'.uMessageRegion'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'EXISTS'
,p_display_when_cond=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT 1',
'  FROM EDC_IP_SHIPMENT_REQ',
' WHERE NVL(ARM_4_QTY, -1) <> :P40_ARM_4_QTY',
'   AND SR_ID = :P40_SR_ID'))
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(9521367017250728017)
,p_event_id=>wwv_flow_imp.id(9521366893445728016)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'$(''#P40_ARM_4_QTY_CHANGE'').show();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(2193781373983259898)
,p_name=>'Set Total No of kits'
,p_event_sequence=>110
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P40_PLACIBO_RUNIN,P40_KITS'
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'change'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(2193781466605259899)
,p_event_id=>wwv_flow_imp.id(2193781373983259898)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P40_RESCUE_MEDICINE'
,p_attribute_01=>'PLSQL_EXPRESSION'
,p_attribute_04=>'NVL(:P40_KITS,0) + NVL(:P40_PLACIBO_RUNIN,0)'
,p_attribute_07=>'P40_KITS,P40_PLACIBO_RUNIN'
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(2009198308831105832)
,p_name=>'set val'
,p_event_sequence=>120
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P40_STUDY_SITE_ID'
,p_condition_element=>'P40_STUDY_SITE_ID'
,p_triggering_condition_type=>'NOT_NULL'
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'change'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(2009198456512105833)
,p_event_id=>wwv_flow_imp.id(2009198308831105832)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P40_QTRY_DEPT'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'V_DEPOT_ID VARCHAR2(4000):=0;',
'V_ET  VARCHAR2(4000);',
'V_DP  VARCHAR2(4000);',
'V_TT NUMBER := 0;',
'V_CT NUMBER;',
'BEGIN',
'SELECT COUNT(STUDY_DEPOT_ID) AS STUDY_DEPOT_ID INTO V_CT',
'            FROM EDC_STUDY_DEPOT',
'                WHERE INSTR('':''||STUDY_SITES||'':'','':''||:P40_STUDY_SITE_ID||'':'',1,1) > 0;',
'                ',
'FOR I IN (SELECT STUDY_DEPOT_ID AS STUDY_DEPOT_ID',
'            FROM EDC_STUDY_DEPOT',
'                WHERE INSTR('':''||STUDY_SITES||'':'','':''||:P40_STUDY_SITE_ID||'':'',1,1) > 0)LOOP',
'    BEGIN',
'        ',
'        SELECT STUDY_DEPOT_ID,NVL(COUNT(IP_ID),0) AS CNT',
'        INTO V_DP,V_ET',
'        FROM EDC_IP_DETAIL',
'            WHERE NVL(IP_STATUS,1) = 1',
'            AND STUDY_DEPOT_ID IN(I.STUDY_DEPOT_ID)',
'            GROUP BY STUDY_DEPOT_ID;',
'        V_TT := V_TT+1;',
'        V_DEPOT_ID := V_DEPOT_ID+V_ET;',
'       -- DOPL(V_DP||'' => ''||V_DEPOT_ID); ',
'       IF V_TT = V_CT THEN',
'            RETURN V_DEPOT_ID;',
'       END IF;',
'    EXCEPTION ',
'        WHEN NO_DATA_FOUND THEN',
'           RETURN 0 ;',
'         WHEN OTHERS THEN',
'           RETURN NULL;',
'    END;',
'END LOOP;',
'END;'))
,p_attribute_07=>'P40_STUDY_SITE_ID'
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(9910409631987419612)
,p_process_sequence=>10
,p_process_point=>'AFTER_HEADER'
,p_process_type=>'NATIVE_FORM_FETCH'
,p_process_name=>'Fetch Row from EDC_IP_SHIPMENT_REQ'
,p_attribute_02=>'EDC_IP_SHIPMENT_REQ'
,p_attribute_03=>'P40_SR_ID'
,p_attribute_04=>'SR_ID'
,p_internal_uid=>9910409631987419612
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(9910410068084419613)
,p_process_sequence=>30
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_FORM_PROCESS'
,p_process_name=>'Process Row of EDC_IP_SHIPMENT_REQ'
,p_attribute_02=>'EDC_IP_SHIPMENT_REQ'
,p_attribute_03=>'P40_SR_ID'
,p_attribute_04=>'SR_ID'
,p_attribute_09=>'P40_SR_ID'
,p_attribute_11=>'I:U'
,p_attribute_12=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_success_message=>'Action Processed.'
,p_internal_uid=>9910410068084419613
,p_process_comment=>':REQUEST NOT IN (''DECLINE'')'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(9910410429184419613)
,p_process_sequence=>40
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_SESSION_STATE'
,p_process_name=>'reset page'
,p_attribute_01=>'CLEAR_CACHE_CURRENT_PAGE'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(9910400600922419591)
,p_internal_uid=>9910410429184419613
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(9910409207874419612)
,p_process_sequence=>50
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'Send to PM for Approval'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'    UPDATE EDC_IP_SHIPMENT_REQ',
'       SET REQUEST_STATUS = ''Open''',
'     WHERE SR_ID = :P40_SR_ID;',
'',
'    COMMIT;',
'',
'    EDC_MAIL.IP_REQUEST_INITIATED(:P40_SR_ID);',
'    ',
'    /*BEGIN',
'        UPDATE EDC_IP_SHIPMENT_REQ',
'           SET PM_APPROVED = 1',
'             , REQUEST_STATUS = ''Open''',
'             , RESPONSE_BY = :APP_USER_NAME',
'             , RESPONSE_DATE = LOCALTIMESTAMP',
'         WHERE SR_ID = :P40_SR_ID;',
'',
'        COMMIT;',
'',
'        --EDC_MAIL.IP_REQUEST_APPROVED(:P40_SR_ID);',
'        EDC_MAIL.IP_REQUEST_INITIATED(:P40_SR_ID);',
'    END;',
'    */',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>':REQUEST IN (''SEND_2_PM'')'
,p_process_when_type=>'EXPRESSION'
,p_process_when2=>'PLSQL'
,p_internal_uid=>9910409207874419612
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(9910410872555419614)
,p_process_sequence=>60
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'DM Approve'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'    UPDATE EDC_IP_SHIPMENT_REQ',
'       SET PM_APPROVED = 1',
'         , RESPONSE_BY = :APP_USER_NAME',
'         , RESPONSE_DATE = LOCALTIMESTAMP',
'     WHERE SR_ID = :P40_SR_ID;',
'',
'    COMMIT;',
'',
'    EDC_MAIL.IP_REQUEST_APPROVED(:P40_SR_ID);',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>':REQUEST IN (''APPROVE'')'
,p_process_when_type=>'EXPRESSION'
,p_process_when2=>'PLSQL'
,p_process_success_message=>'Shipment Approved'
,p_internal_uid=>9910410872555419614
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(9910408876937419611)
,p_process_sequence=>70
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'DM Decline'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'    UPDATE EDC_IP_SHIPMENT_REQ',
'       SET PM_APPROVED = -1',
'         , DECLINE_REASON = :P40_DECLINE_REASON_TEMP',
'         , RESPONSE_BY = :APP_USER_NAME',
'         , RESPONSE_DATE = LOCALTIMESTAMP',
'     WHERE SR_ID = :P40_SR_ID;',
'',
'    EDC_MAIL.IP_REQUEST_DECLINED(:P40_SR_ID);',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>':REQUEST IN (''DECLINE'')'
,p_process_when_type=>'EXPRESSION'
,p_process_when2=>'PLSQL'
,p_process_success_message=>'Shipment Declined'
,p_internal_uid=>9910408876937419611
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(9911230230606911341)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'SHOW_REASON_FOR_CHANGE'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    V_SQL CLOB;',
'    CURSOR C1 IS (SELECT ITEM_NAME',
'                       , SUBSTR(ITEM_NAME,1,INSTR(ITEM_NAME,''_CHANGE'',-1,1)-1) ITEM',
'                    FROM APEX_APPLICATION_PAGE_ITEMS',
'                   WHERE ITEM_NAME LIKE ''%CHANGE%''',
'                     AND PAGE_ID = :APP_PAGE_ID',
'                     AND APPLICATION_ID = :APP_ID',
'                 );',
'BEGIN',
'   -- IF :APP_EDC_ROLE_ID IN (13, 19, 23 /* Admin, PM, Medical Monitor*/) THEN',
'        --HTP.P(''<script language="Javascript">'');',
'        FOR I IN C1 LOOP',
'            V_SQL := ''$(''''#''||I.ITEM||'''''').change(function(){',
'                          $(''''#''||I.ITEM_NAME||'''''').show();',
'                          $(''''#''||I.ITEM_NAME||''_LABEL'''').show();',
'                      });'';',
'',
'            HTP.P(V_SQL);',
'        END LOOP;',
'        -- HTP.P(''</script>'');',
'   -- END IF;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>9911230230606911341
);
wwv_flow_imp.component_end;
end;
/
