prompt --application/shared_components/navigation/lists/admin_configuration
begin
--   Manifest
--     LIST: Admin_configuration
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>666903967469575309
,p_default_application_id=>10021010
,p_default_id_offset=>759714394172364641
,p_default_owner=>'SUN_21010_DEV'
);
wwv_flow_imp_shared.create_list(
 p_id=>wwv_flow_imp.id(11045440166091273288)
,p_name=>'Admin_configuration'
,p_list_status=>'PUBLIC'
,p_version_scn=>1
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045440486493273291)
,p_list_item_display_sequence=>5
,p_list_item_link_text=>'List Of Values'
,p_list_item_link_target=>'f?p=&APP_ID.:14:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/shapes_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'14,15'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045440779554273292)
,p_list_item_display_sequence=>10
,p_list_item_link_text=>'Indication'
,p_list_item_link_target=>'f?p=&APP_ID.:9:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/edit_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'9,10'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045441069545273293)
,p_list_item_display_sequence=>20
,p_list_item_link_text=>'Sponsor'
,p_list_item_link_target=>'f?p=&APP_ID.:22:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/globe_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'22,23'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045441371392273293)
,p_list_item_display_sequence=>30
,p_list_item_link_text=>'Investigator'
,p_list_item_link_target=>'f?p=&APP_ID.:24:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/user_green_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'24,25,171,172'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045441687733273293)
,p_list_item_display_sequence=>40
,p_list_item_link_text=>'CRF Status'
,p_list_item_link_target=>'f?p=&APP_ID.:26:&SESSION.::&DEBUG.:RP,26:::'
,p_list_item_icon=>'menu/chart_pie_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'26'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045441971365273293)
,p_list_item_display_sequence=>50
,p_list_item_link_text=>'Note Category'
,p_list_item_link_target=>'f?p=&APP_ID.:27:&SESSION.::&DEBUG.:RP,27:::'
,p_list_item_icon=>'menu/memo_32.gif'
,p_list_item_disp_cond_type=>'NEVER'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'27,29'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045442283073273293)
,p_list_item_display_sequence=>60
,p_list_item_link_text=>'Parameters'
,p_list_item_link_target=>'f?p=&APP_ID.:30:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/logic_32.gif'
,p_list_item_disp_cond_type=>'NEVER'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'30'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045442578381273293)
,p_list_item_display_sequence=>70
,p_list_item_link_text=>'Mail Format'
,p_list_item_link_target=>'f?p=&APP_ID.:31:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/mail_32.gif'
,p_list_item_disp_cond_type=>'NEVER'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'31,32'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045443174469273294)
,p_list_item_display_sequence=>90
,p_list_item_link_text=>'User'
,p_list_item_link_target=>'f?p=&APP_ID.:34:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/user_yellow_32.gif'
,p_list_item_disp_cond_type=>'NEVER'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'34,35'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(11045443461548273294)
,p_list_item_display_sequence=>100
,p_list_item_link_text=>'Study'
,p_list_item_link_target=>'f?p=&APP_ID.:195:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/books_32.gif'
,p_list_item_disp_cond_type=>'NEVER'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'195,196'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(4133094270205172560)
,p_list_item_display_sequence=>110
,p_list_item_link_text=>'Approve Workflow'
,p_list_item_link_target=>'f?p=&APP_ID.:98:&SESSION.::&DEBUG.:98:::'
,p_list_item_icon=>'menu/manage_service_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'98,103'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(2696476992871325042)
,p_list_item_display_sequence=>120
,p_list_item_link_text=>'Document Group Master'
,p_list_item_link_target=>'f?p=&APP_ID.:117:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/dynamic_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'117,118'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(2007237853247395817)
,p_list_item_display_sequence=>130
,p_list_item_link_text=>'Region Master'
,p_list_item_link_target=>'f?p=&APP_ID.:131:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/navigation_page_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'131,132'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(2007267142882165229)
,p_list_item_display_sequence=>140
,p_list_item_link_text=>'Depot Master'
,p_list_item_link_target=>'f?p=&APP_ID.:133:&SESSION.::&DEBUG.:RP:::'
,p_list_item_icon=>'menu/todo_32.gif'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'133,134'
);
wwv_flow_imp.component_end;
end;
/
