prompt --application/pages/page_00042
begin
--   Manifest
--     PAGE: 00042
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>666903967469575309
,p_default_application_id=>10021010
,p_default_id_offset=>1100950768141504093
,p_default_owner=>'SUN_21010_DEV'
);
wwv_flow_imp_page.create_page(
 p_id=>42
,p_tab_set=>'TS1'
,p_name=>'Page Access'
,p_step_title=>'Page Access'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_first_item=>'AUTO_FIRST_ITEM'
,p_autocomplete_on_off=>'ON'
,p_page_template_options=>'#DEFAULT#'
,p_nav_list_template_options=>'#DEFAULT#'
,p_help_text=>'No help is available for this page.'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11996785804758278799)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(12146130233942911979)
,p_plug_display_sequence=>1.5
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(12146139932546912016)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(12146137930501911991)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12146579237278299768)
,p_plug_name=>'Page Access'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(12146132256919911981)
,p_plug_display_sequence=>10
,p_plug_new_grid_row=>false
,p_plug_display_point=>'BODY_3'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT ',
'   "EDC_GROUP_ACCESS"."GRP_ACC_ID" "GRP_ACC_ID", ',
'   "EDC_GROUP_ACCESS"."STUDY_ID" "STUDY_ID", ',
'   "EDC_GROUP_ACCESS"."GRP_ID" "GRP_ID", ',
'   "EDC_GROUP_ACCESS"."ROLE_ID" "ROLE_ID", ',
'   "EDC_GROUP_ACCESS"."ROLE_TYPE" "ROLE_TYPE", ',
'   "EDC_GROUP_ACCESS"."CAN_SEE" "CAN_SEE", ',
'   "EDC_GROUP_ACCESS"."CAN_CREATE" "CAN_CREATE", ',
'   "EDC_GROUP_ACCESS"."CAN_UPDATE" "CAN_UPDATE", ',
'   "EDC_GROUP_ACCESS"."CAN_DELETE" "CAN_DELETE", ',
'   "EDC_GROUP_ACCESS"."CAN_QUERY" "CAN_QUERY", ',
'   "EDC_GROUP_ACCESS"."CAN_LOCKUNLOCK" "CAN_LOCKUNLOCK", ',
'   "EDC_GROUP_ACCESS"."CAN_SUBMIT" "CAN_SUBMIT", ',
'   "EDC_GROUP_ACCESS"."CAN_MONITOR" "CAN_MONITOR", ',
'   "EDC_GROUP_ACCESS"."CAN_FREEZE" "CAN_FREEZE", ',
'   "EDC_GROUP_ACCESS"."CREATED_BY" "CREATED_BY", ',
'   "EDC_GROUP_ACCESS"."CREATED_DT" "CREATED_DT", ',
'   "EDC_GROUP_ACCESS"."UPDATED_BY" "UPDATED_BY", ',
'   "EDC_GROUP_ACCESS"."UPDATED_DT" "UPDATED_DT"',
'FROM ',
'   EDC_GROUP_ACCESS',
'--WHERE STUDY_ID = :APP_EDC_STUDY_ID'))
,p_plug_source_type=>'NATIVE_IR'
,p_plug_query_show_nulls_as=>' - '
,p_pagination_display_position=>'BOTTOM_RIGHT'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(12146579448008299768)
,p_name=>'Page Access'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_fixed_header=>'NONE'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_pivot=>'N'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML'
,p_enable_mail_download=>'Y'
,p_detail_link_text=>'<img src="#IMAGE_PREFIX#menu/pencil16x16.gif" alt="" />'
,p_allow_exclude_null_values=>'N'
,p_allow_hide_extra_columns=>'N'
,p_icon_view_columns_per_row=>1
,p_owner=>'KRUNAL.BHATT'
,p_internal_uid=>149955723523733988
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146579528812299768)
,p_db_column_name=>'GRP_ACC_ID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Edit'
,p_column_link=>'f?p=&APP_ID.:43:&SESSION.::&DEBUG.:RP:P43_GRP_ACC_ID:#GRP_ACC_ID#'
,p_column_linktext=>'<img src="#IMAGE_PREFIX#e2.gif"  border="0">'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_static_id=>'GRP_ACC_ID'
,p_use_as_row_header=>'N'
,p_security_scheme=>wwv_flow_imp.id(12146159132002328484)
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146579628127299769)
,p_db_column_name=>'STUDY_ID'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Study Id'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_static_id=>'STUDY_ID'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146579733355299769)
,p_db_column_name=>'GRP_ID'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Group'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_tz_dependent=>'N'
,p_static_id=>'GRP_ID'
,p_rpt_named_lov=>wwv_flow_imp.id(12146586136559299786)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146579943261299770)
,p_db_column_name=>'ROLE_TYPE'
,p_display_order=>4
,p_column_identifier=>'E'
,p_column_label=>'Type'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_tz_dependent=>'N'
,p_static_id=>'ROLE_TYPE'
,p_rpt_named_lov=>wwv_flow_imp.id(12146367732574503277)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146579825964299770)
,p_db_column_name=>'ROLE_ID'
,p_display_order=>5
,p_column_identifier=>'D'
,p_column_label=>'Role'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_tz_dependent=>'N'
,p_static_id=>'ROLE_ID'
,p_rpt_named_lov=>wwv_flow_imp.id(12146564138299202672)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580032893299770)
,p_db_column_name=>'CAN_SEE'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'View'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_SEE'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580133239299770)
,p_db_column_name=>'CAN_CREATE'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Create'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_CREATE'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580255717299770)
,p_db_column_name=>'CAN_UPDATE'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Update'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_UPDATE'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580327399299770)
,p_db_column_name=>'CAN_DELETE'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Delete'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_DELETE'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580443481299770)
,p_db_column_name=>'CAN_QUERY'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Query'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_QUERY'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580536436299770)
,p_db_column_name=>'CAN_LOCKUNLOCK'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Review'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_LOCKUNLOCK'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580643666299770)
,p_db_column_name=>'CAN_SUBMIT'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Submit'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_SUBMIT'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580751141299770)
,p_db_column_name=>'CAN_MONITOR'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Dispense'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_MONITOR'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146581227204299771)
,p_db_column_name=>'CAN_FREEZE'
,p_display_order=>23
,p_column_identifier=>'R'
,p_column_label=>'Approve'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_static_id=>'CAN_FREEZE'
,p_rpt_named_lov=>wwv_flow_imp.id(11671084529125376187)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580853817299771)
,p_db_column_name=>'CREATED_BY'
,p_display_order=>33
,p_column_identifier=>'N'
,p_column_label=>'Created By'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_static_id=>'CREATED_BY'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146580957152299771)
,p_db_column_name=>'CREATED_DT'
,p_display_order=>43
,p_column_identifier=>'O'
,p_column_label=>'Created Dt'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_static_id=>'CREATED_DT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146581039950299771)
,p_db_column_name=>'UPDATED_BY'
,p_display_order=>53
,p_column_identifier=>'P'
,p_column_label=>'Updated By'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_static_id=>'UPDATED_BY'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(12146581140021299771)
,p_db_column_name=>'UPDATED_DT'
,p_display_order=>63
,p_column_identifier=>'Q'
,p_column_label=>'Updated Dt'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_static_id=>'UPDATED_DT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(12146581335259299771)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'1499577'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_display_rows=>15
,p_report_columns=>'GRP_ACC_ID:GRP_ID:ROLE_TYPE:ROLE_ID:CAN_SEE:CAN_CREATE:CAN_UPDATE:CAN_DELETE:CAN_QUERY:CAN_LOCKUNLOCK:CAN_SUBMIT:'
);
wwv_flow_imp_page.create_worksheet_condition(
 p_id=>wwv_flow_imp.id(9941491571507050019)
,p_report_id=>wwv_flow_imp.id(12146581335259299771)
,p_name=>'Row text contains ''crc'''
,p_condition_type=>'SEARCH'
,p_allow_delete=>'Y'
,p_expr=>'crc'
,p_enabled=>'Y'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12146581735519299773)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(12146130233942911979)
,p_plug_display_sequence=>1
,p_plug_new_grid_row=>false
,p_plug_new_grid_column=>false
,p_plug_display_column=>1
,p_plug_display_point=>'REGION_POSITION_01'
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(12146137930501911991)
,p_plug_display_condition_type=>'NEVER'
,p_plug_read_only_when_type=>'NEVER'
);
wwv_flow_imp_page.create_report_region(
 p_id=>wwv_flow_imp.id(12146581936976299775)
,p_name=>'Page Access - Disabled'
,p_template=>wwv_flow_imp.id(12146132256919911981)
,p_display_sequence=>10
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_new_grid_row=>false
,p_new_grid_column=>false
,p_display_column=>2
,p_display_point=>'BODY_3'
,p_source_type=>'NATIVE_SQL_REPORT'
,p_query_type=>'SQL'
,p_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT ',
'   "EDC_GROUP_ACCESS"."GRP_ACC_ID" "GRP_ACC_ID", ',
'   "EDC_GROUP_ACCESS"."STUDY_ID" "STUDY_ID", ',
'   "EDC_GROUP_ACCESS"."GRP_ID" "GRP_ID", ',
'   "EDC_GROUP_ACCESS"."ROLE_ID" "ROLE_ID", ',
'   "EDC_GROUP_ACCESS"."ROLE_TYPE" "ROLE_TYPE", ',
'   "EDC_GROUP_ACCESS"."CAN_SEE" "CAN_SEE", ',
'   "EDC_GROUP_ACCESS"."CAN_CREATE" "CAN_CREATE", ',
'   "EDC_GROUP_ACCESS"."CAN_UPDATE" "CAN_UPDATE", ',
'   "EDC_GROUP_ACCESS"."CAN_DELETE" "CAN_DELETE", ',
'   "EDC_GROUP_ACCESS"."CAN_QUERY" "CAN_QUERY", ',
'   "EDC_GROUP_ACCESS"."CAN_LOCKUNLOCK" "CAN_LOCKUNLOCK", ',
'   "EDC_GROUP_ACCESS"."CAN_SUBMIT" "CAN_SUBMIT", ',
'   "EDC_GROUP_ACCESS"."CAN_MONITOR" "CAN_MONITOR", ',
'   "EDC_GROUP_ACCESS"."CREATED_BY" "CREATED_BY", ',
'   "EDC_GROUP_ACCESS"."CREATED_DT" "CREATED_DT", ',
'   "EDC_GROUP_ACCESS"."UPDATED_BY" "UPDATED_BY", ',
'   "EDC_GROUP_ACCESS"."UPDATED_DT" "UPDATED_DT"',
'FROM ',
'   "EDC_GROUP_ACCESS"',
''))
,p_display_condition_type=>'NEVER'
,p_fixed_header=>'NONE'
,p_lazy_loading=>false
,p_query_row_template=>wwv_flow_imp.id(12146133941701911984)
,p_query_num_rows=>20
,p_query_options=>'DERIVED_REPORT_COLUMNS'
,p_query_break_cols=>'0'
,p_query_no_data_found=>'No data found.'
,p_query_num_rows_type=>'ROW_RANGES_IN_SELECT_LIST'
,p_query_row_count_max=>500
,p_pagination_display_position=>'BOTTOM_RIGHT'
,p_break_type_flag=>'DEFAULT_BREAK_FORMATTING'
,p_csv_output=>'N'
,p_plug_query_strip_html=>'Y'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582136742299775)
,p_query_column_id=>1
,p_column_alias=>'GRP_ACC_ID'
,p_column_display_sequence=>1
,p_column_heading=>'Edit'
,p_use_as_row_header=>'N'
,p_column_link=>'f?p=#APP_ID#:43:#APP_SESSION#:::RP:P43_GRP_ACC_ID:#GRP_ACC_ID#'
,p_column_linktext=>'<img src="#IMAGE_PREFIX#e2.gif"  border="0">'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'GRP_ACC_ID'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582246039299776)
,p_query_column_id=>2
,p_column_alias=>'STUDY_ID'
,p_column_display_sequence=>2
,p_use_as_row_header=>'N'
,p_disable_sort_column=>'N'
,p_derived_column=>'N'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'STUDY_ID'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582344592299776)
,p_query_column_id=>3
,p_column_alias=>'GRP_ID'
,p_column_display_sequence=>3
,p_column_heading=>'Group'
,p_use_as_row_header=>'N'
,p_disable_sort_column=>'N'
,p_derived_column=>'N'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'GRP_ID'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582454872299776)
,p_query_column_id=>4
,p_column_alias=>'ROLE_ID'
,p_column_display_sequence=>5
,p_column_heading=>'Role'
,p_use_as_row_header=>'N'
,p_disable_sort_column=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'NO'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'ROLE_ID'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582551662299776)
,p_query_column_id=>5
,p_column_alias=>'ROLE_TYPE'
,p_column_display_sequence=>4
,p_column_heading=>'Type'
,p_use_as_row_header=>'N'
,p_disable_sort_column=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'NO'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'ROLE_TYPE'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582648240299776)
,p_query_column_id=>6
,p_column_alias=>'CAN_SEE'
,p_column_display_sequence=>6
,p_column_heading=>'View'
,p_use_as_row_header=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'YES'
,p_lov_null_text=>'No'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CAN_SEE'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582736267299776)
,p_query_column_id=>7
,p_column_alias=>'CAN_CREATE'
,p_column_display_sequence=>7
,p_column_heading=>'Create'
,p_use_as_row_header=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'YES'
,p_lov_null_text=>'No'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CAN_CREATE'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582842837299776)
,p_query_column_id=>8
,p_column_alias=>'CAN_UPDATE'
,p_column_display_sequence=>8
,p_column_heading=>'Update'
,p_use_as_row_header=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'YES'
,p_lov_null_text=>'No'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CAN_UPDATE'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146582942394299776)
,p_query_column_id=>9
,p_column_alias=>'CAN_DELETE'
,p_column_display_sequence=>9
,p_column_heading=>'Delete'
,p_use_as_row_header=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'YES'
,p_lov_null_text=>'No'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CAN_DELETE'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146583027043299776)
,p_query_column_id=>10
,p_column_alias=>'CAN_QUERY'
,p_column_display_sequence=>10
,p_column_heading=>'Query'
,p_use_as_row_header=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'YES'
,p_lov_null_text=>'No'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CAN_QUERY'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146583132842299776)
,p_query_column_id=>11
,p_column_alias=>'CAN_LOCKUNLOCK'
,p_column_display_sequence=>11
,p_column_heading=>'Lock/Unlock'
,p_use_as_row_header=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'YES'
,p_lov_null_text=>'No'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CAN_LOCKUNLOCK'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146583240735299776)
,p_query_column_id=>12
,p_column_alias=>'CAN_SUBMIT'
,p_column_display_sequence=>12
,p_column_heading=>'Submit'
,p_use_as_row_header=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'YES'
,p_lov_null_text=>'No'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CAN_SUBMIT'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146583356954299776)
,p_query_column_id=>13
,p_column_alias=>'CAN_MONITOR'
,p_column_display_sequence=>13
,p_column_heading=>'Monitor'
,p_use_as_row_header=>'N'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_lov_show_nulls=>'YES'
,p_lov_null_text=>'No'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CAN_MONITOR'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146583445711299776)
,p_query_column_id=>14
,p_column_alias=>'CREATED_BY'
,p_column_display_sequence=>14
,p_column_heading=>'Created By'
,p_use_as_row_header=>'N'
,p_hidden_column=>'Y'
,p_lov_show_nulls=>'NO'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CREATED_BY'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146583543861299776)
,p_query_column_id=>15
,p_column_alias=>'CREATED_DT'
,p_column_display_sequence=>15
,p_column_heading=>'Created Dt'
,p_use_as_row_header=>'N'
,p_hidden_column=>'Y'
,p_lov_show_nulls=>'NO'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'CREATED_DT'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146583649128299777)
,p_query_column_id=>16
,p_column_alias=>'UPDATED_BY'
,p_column_display_sequence=>16
,p_column_heading=>'Updated By'
,p_use_as_row_header=>'N'
,p_hidden_column=>'Y'
,p_lov_show_nulls=>'NO'
,p_include_in_export=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'UPDATED_BY'
);
wwv_flow_imp_page.create_report_columns(
 p_id=>wwv_flow_imp.id(12146583740843299777)
,p_query_column_id=>17
,p_column_alias=>'UPDATED_DT'
,p_column_display_sequence=>17
,p_column_heading=>'Updated Dt'
,p_use_as_row_header=>'N'
,p_hidden_column=>'Y'
,p_ref_schema=>'SUN_21010_DEV'
,p_ref_table_name=>'EDC_GROUP_ACCESS'
,p_ref_column_name=>'UPDATED_DT'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12146871537127105357)
,p_plug_name=>'&nbsp;'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-right:5px;"'
,p_plug_template=>wwv_flow_imp.id(12146131749834911981)
,p_plug_display_sequence=>5
,p_plug_display_point=>'BODY_3'
,p_list_id=>wwv_flow_imp.id(12146507135895073841)
,p_plug_source_type=>'NATIVE_LIST'
,p_list_template_id=>wwv_flow_imp.id(12146135651272911987)
,p_plug_query_headings_type=>'QUERY_COLUMNS'
,p_plug_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_plug_query_show_nulls_as=>' - '
,p_pagination_display_position=>'BOTTOM_RIGHT'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(12146581550188299772)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(12146579237278299768)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(12146136944085911990)
,p_button_image_alt=>'Create'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_alignment=>'RIGHT'
,p_button_redirect_url=>'f?p=&APP_ID.:43:&SESSION.::&DEBUG.:43::'
,p_security_scheme=>wwv_flow_imp.id(12146158755186328484)
);
wwv_flow_imp_page.create_page_computation(
 p_id=>wwv_flow_imp.id(12146586041287299784)
,p_computation_sequence=>1
,p_computation_item=>'P43_GRP_ACC_ID'
,p_computation_type=>'STATIC_ASSIGNMENT'
,p_compute_when=>'CREATE'
,p_compute_when_type=>'REQUEST_EQUALS_CONDITION'
);
wwv_flow_imp.component_end;
end;
/
