prompt --application/pages/page_00112
begin
--   Manifest
--     PAGE: 00112
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.0'
,p_default_workspace_id=>666903967469575309
,p_default_application_id=>10021010
,p_default_id_offset=>1100950768141504093
,p_default_owner=>'SUN_21010_DEV'
);
wwv_flow_imp_page.create_page(
 p_id=>112
,p_tab_set=>'TS1'
,p_name=>'ePRO - Audit Trail Report'
,p_step_title=>'ePRO - Audit Trail Report'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_page_template_options=>'#DEFAULT#'
,p_help_text=>'No help is available for this page.'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12010702296863136607)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(12146130233942911979)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(12146139932546912016)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(12146137930501911991)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12010702864805136609)
,p_plug_name=>'ePRO - Audit Trail Report'
,p_region_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-left:10px;"'
,p_plug_template=>wwv_flow_imp.id(12146132256919911981)
,p_plug_display_sequence=>20
,p_plug_new_grid_row=>false
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT',
'       TO_CHAR(SYSDATE,''DD-MON-YYYY'') "GENERATED_DATE",',
'       (SELECT STUDY_SITE_ID FROM EDC_PATIENT_PROFILE ',
'                             WHERE PATIENT_PROFILE_ID = (SELECT PATIENT_PROFILE_ID FROM EDC_PATIENT_DIARY',
'                                                         WHERE PATIENT_DIARY_ID = A.PATIENT_DIARY_ID AND STUDY_ID = :APP_EDC_STUDY_ID)) "STUDY_SITE_ID",',
'       (SELECT SCRNO FROM EDC_PATIENT_PROFILE ',
'                     WHERE PATIENT_PROFILE_ID = (SELECT PATIENT_PROFILE_ID FROM EDC_PATIENT_DIARY',
'                                                 WHERE PATIENT_DIARY_ID = A.PATIENT_DIARY_ID AND STUDY_ID = :APP_EDC_STUDY_ID))"SCRNO",',
'       (SELECT RANDOMNO FROM EDC_PATIENT_PROFILE ',
'                        WHERE PATIENT_PROFILE_ID = A.PATIENT_PROFILE_ID AND STUDY_ID = :APP_EDC_STUDY_ID) "RANDOMIZATION_NO",',
'       (SELECT SCHEDULE_TITLE FROM EDC_PATIENT_DIARY',
'                           WHERE PATIENT_DIARY_ID = A.PATIENT_DIARY_ID AND STUDY_ID = :APP_EDC_STUDY_ID) "SCHEDULE_TITLE",',
'       (SELECT CRF_NAME FROM EDC_CRF_MASTER ',
'                        WHERE CRF_TABLE_NAME = A.TABLE_NAME AND STUDY_ID = :APP_EDC_STUDY_ID AND CRF_ID = (SELECT MIN(CRF_ID) FROM EDC_CRF_MASTER WHERE STUDY_ID = :APP_EDC_STUDY_ID AND CRF_TABLE_NAME = A.TABLE_NAME)) "PANEL_NAME",',
'       CASE',
'       WHEN A.COLUMN_NAME = ''SECTION_STATUS'' THEN ''Section Status''',
'       WHEN TABLE_NAME IN (SELECT DISTINCT CRF_TABLE_NAME FROM EDC_CRF_MASTER WHERE STUDY_ID = :APP_EDC_STUDY_ID) THEN',
'       (SELECT ITEM_LABEL FROM EDC_CRF_ITEMS',
'        WHERE CRF_TABLE_NAME = A.TABLE_NAME',
'        AND COLUMN_NAME = A.COLUMN_NAME',
'        AND STUDY_ID = :APP_EDC_STUDY_ID) END "FIELD_NAME",',
'        ',
'       CASE WHEN A.COLUMN_NAME = ''SECTION_STATUS'' THEN',
'       DECODE(OLD_VALUE,2,''Incomplete'',3,''Complete'',4,''Data Submitted'',5,''Query Generated by CRA'',6,''CRA Reviewed'',7,''Query Generated by DM'',',
'       8,''DM Reviewed'',9,''PI Signed Off'',10,''Locked'',11,''Unlocked'')',
'       ELSE',
'       OLD_VALUE END "OLD_VALUE",',
'       ',
'       CASE WHEN A.COLUMN_NAME = ''SECTION_STATUS'' THEN',
'       DECODE(NEW_VALUE,2,''Incomplete'',3,''Complete'',4,''Data Submitted'',5,''Query Generated by CRA'',6,''CRA Reviewed'',7,''Query Generated by DM'',',
'       8,''DM Reviewed'',9,''PI Signed Off'',10,''Locked'',11,''Unlocked'')',
'       ELSE',
'       NEW_VALUE END "NEW_VALUE",',
'       ',
'       REASON,',
'       USERNAME "PERFORMED_BY",',
'       ',
'       /*CASE WHEN UPPER(A.USERNAME) IN (SELECT UPPER(USERNAME) FROM EDC_USERS WHERE ROLE_LEVEL = ''A'') THEN',
'       ''Admin''',
'       ELSE',
'       (SELECT ROLE_NAME FROM EDC_USER_ROLE',
'                         WHERE role_id = (SELECT CONTACT_ROLE ',
'                                          FROM EDC_STUDY_CONTACT ',
'                                          WHERE upper(username) = upper(A.USERNAME)',
'                                         AND STUDY_ID = :APP_EDC_STUDY_ID))',
'       END "ROLE",*/',
'       TO_CHAR(log_timestamp,''DD-MON-YYYY HH24:MI:SS'') "PERFORMED_ON",',
'       AUDIT_LOG_ID,',
'       A.ACTION "ACTION"',
'FROM AUDIT_TRAIL A',
'WHERE A.COLUMN_NAME NOT IN (''PATIENT_PROFILE_ID'',''STUDY_ID'',''PATIENT_DIARY_ID'',''CREATED_BY'',''CREATED_DT'',',
'                            ''CREATED_ON'',''UPDATED_ON'',''UPDATED_DT'',''UPDATED_BY'',''CRF_STATUS'',''CRF_SIGNED_DATE'')',
'AND A.COLUMN_NAME NOT IN (SELECT CRF_TABLE_PK_COL FROM EDC_CRF_MASTER WHERE STUDY_ID = :APP_EDC_STUDY_ID)',
'AND A.COLUMN_NAME NOT IN (SELECT COLUMN_NAME FROM EDC_CRF_ITEMS WHERE ITEM_TYPE = ''LABEL'')',
'AND TABLE_NAME NOT IN (''EDC_PATIENT_DIARY'')',
'AND TABLE_NAME NOT IN (''EDC_PATIENT_PROFILE'')',
'AND A.STUDY_ID = :APP_EDC_STUDY_ID',
'AND A.PATIENT_DIARY_ID IN (select X.PATIENT_DIARY_ID FROM EDC_PATIENT_DIARY X,EDC_PATIENT_PROFILE Y',
'WHERE X.PATIENT_PROFILE_ID = Y.PATIENT_PROFILE_ID',
'AND Y.STUDY_SITE_ID = DECODE(:P112_SITE,999999,Y.STUDY_SITE_ID,:P112_SITE)',
')',
'AND STUDY_SITE_ID = DECODE(:P112_SITE,999999,STUDY_SITE_ID,:P112_SITE)'))
,p_plug_source_type=>'NATIVE_IR'
,p_ajax_items_to_submit=>'APP_EDC_STUDY_ID,APP_ID,P112_SITE'
,p_prn_content_disposition=>'ATTACHMENT'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(12010702957995136609)
,p_name=>'Subject Visits'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_max_rows_per_page=>'20'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y_OF_Z'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'NIKHIL.BUTANI'
,p_internal_uid=>8464257450973813268
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790500260030332153)
,p_db_column_name=>'STUDY_SITE_ID'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Site'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(12152747731580527615)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790501496289332161)
,p_db_column_name=>'SCRNO'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Screening<br/>Number'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513009676422252)
,p_db_column_name=>'GENERATED_DATE'
,p_display_order=>15
,p_column_identifier=>'AN'
,p_column_label=>'Generated Date'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513110675422253)
,p_db_column_name=>'RANDOMIZATION_NO'
,p_display_order=>25
,p_column_identifier=>'AO'
,p_column_label=>'Randomization No'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513383972422255)
,p_db_column_name=>'PANEL_NAME'
,p_display_order=>45
,p_column_identifier=>'AQ'
,p_column_label=>'Panel Name'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513441850422256)
,p_db_column_name=>'FIELD_NAME'
,p_display_order=>55
,p_column_identifier=>'AR'
,p_column_label=>'Field Name'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513524164422257)
,p_db_column_name=>'OLD_VALUE'
,p_display_order=>65
,p_column_identifier=>'AS'
,p_column_label=>'Old Value'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513632618422258)
,p_db_column_name=>'NEW_VALUE'
,p_display_order=>75
,p_column_identifier=>'AT'
,p_column_label=>'New Value'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513760740422259)
,p_db_column_name=>'REASON'
,p_display_order=>85
,p_column_identifier=>'AU'
,p_column_label=>'Reason for Change'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513838560422260)
,p_db_column_name=>'PERFORMED_BY'
,p_display_order=>95
,p_column_identifier=>'AV'
,p_column_label=>'Performed By'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790513961143422261)
,p_db_column_name=>'PERFORMED_ON'
,p_display_order=>105
,p_column_identifier=>'AW'
,p_column_label=>'Performed On'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790514014072422262)
,p_db_column_name=>'AUDIT_LOG_ID'
,p_display_order=>115
,p_column_identifier=>'AX'
,p_column_label=>'Audit Log Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790514151748422263)
,p_db_column_name=>'ACTION'
,p_display_order=>125
,p_column_identifier=>'AY'
,p_column_label=>'Action'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3790515001299422271)
,p_db_column_name=>'SCHEDULE_TITLE'
,p_display_order=>135
,p_column_identifier=>'AZ'
,p_column_label=>'Schedule Title'
,p_column_type=>'STRING'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(3551284924513787413)
,p_application_user=>'APXWS_ALTERNATIVE'
,p_name=>'Report for Updated Records'
,p_report_seq=>10
,p_report_alias=>'2578090'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_display_rows=>20
,p_report_columns=>'SCRNO:RANDOMIZATION_NO:SCHEDULE_TITLE:PANEL_NAME:FIELD_NAME:OLD_VALUE:NEW_VALUE:REASON:PERFORMED_BY:PERFORMED_ON:ACTION:'
,p_sort_column_1=>'SCRNO'
,p_sort_direction_1=>'ASC'
,p_sort_column_2=>'SCHEDULE_TITLE'
,p_sort_direction_2=>'ASC'
,p_sort_column_3=>'PANEL_NAME'
,p_sort_direction_3=>'ASC'
,p_sort_column_4=>'PERFORMED_ON'
,p_sort_direction_4=>'ASC'
,p_sort_column_5=>'0'
,p_sort_direction_5=>'ASC'
,p_sort_column_6=>'0'
,p_sort_direction_6=>'ASC'
,p_break_on=>'0:0:0:0:0'
,p_break_enabled_on=>'0:0:0:0:0'
);
wwv_flow_imp_page.create_worksheet_condition(
 p_id=>wwv_flow_imp.id(3551285357208787415)
,p_report_id=>wwv_flow_imp.id(3551284924513787413)
,p_condition_type=>'FILTER'
,p_allow_delete=>'Y'
,p_column_name=>'ACTION'
,p_operator=>'='
,p_expr=>'UPDATE'
,p_condition_sql=>'"ACTION" = #APXWS_EXPR#'
,p_condition_display=>'#APXWS_COL_NAME# = ''UPDATE''  '
,p_enabled=>'Y'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(12010709774961137542)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'2440575'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_display_rows=>20
,p_report_columns=>'SCRNO:RANDOMIZATION_NO:SCHEDULE_TITLE:PANEL_NAME:FIELD_NAME:OLD_VALUE:NEW_VALUE:REASON:PERFORMED_BY:PERFORMED_ON:ACTION:'
,p_sort_column_1=>'SCRNO'
,p_sort_direction_1=>'ASC'
,p_sort_column_2=>'SCHEDULE_TITLE'
,p_sort_direction_2=>'ASC'
,p_sort_column_3=>'PANEL_NAME'
,p_sort_direction_3=>'ASC'
,p_sort_column_4=>'PERFORMED_ON'
,p_sort_direction_4=>'ASC'
,p_sort_column_5=>'0'
,p_sort_direction_5=>'ASC'
,p_sort_column_6=>'0'
,p_sort_direction_6=>'ASC'
,p_break_on=>'0:0:0:0:0'
,p_break_enabled_on=>'0:0:0:0:0'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12010729982725241569)
,p_plug_name=>'Study Reports List'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-right:5px;"'
,p_plug_template=>wwv_flow_imp.id(12146131826484911981)
,p_plug_display_sequence=>10
,p_list_id=>wwv_flow_imp.id(12162256056595676308)
,p_plug_source_type=>'NATIVE_LIST'
,p_list_template_id=>wwv_flow_imp.id(12162463639986384308)
,p_plug_query_headings_type=>'QUERY_COLUMNS'
,p_plug_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_plug_query_show_nulls_as=>' - '
,p_pagination_display_position=>'BOTTOM_RIGHT'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(3790766643552718385)
,p_name=>'P112_SITE'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(12010702864805136609)
,p_prompt=>'Sites'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select d, r from (SELECT a.site_number || '' ('' || FIRST_NAME || '' '' || LAST_NAME || '' - '' || b.invname || '')'' D',
'     , A.STUDY_SITE_ID R, ''1'' s',
'  FROM EDC_STUDY_SITES A,',
'       EDC_SITES B',
' WHERE A.SITE_ID = B.SITE_ID',
'   AND A.STUDY_ID = :APP_EDC_STUDY_ID',
'   AND EDC_AUTH_PKG.CHECK_STUDY_SITE_ACCESS(A.STUDY_SITE_ID) <> 0',
'union',
'select ''All Sites'' D, 999999 r, ''0'' s',
'from dual',
'order by s, d)'))
,p_lov_display_null=>'YES'
,p_lov_null_text=>'--Select--'
,p_cHeight=>1
,p_label_alignment=>'RIGHT-CENTER'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_imp.id(12146136537200911989)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'NO'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'SUBMIT'
,p_attribute_03=>'Y'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(3790507266847332211)
,p_name=>'Download PDF_1'
,p_event_sequence=>20
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_imp.id(10506106941451303413)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'click'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(3790507717945332213)
,p_event_id=>wwv_flow_imp.id(3790507266847332211)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'window.open(''../JasperReportsIntegration/report?_repName=SUN_21010_DEV/DICLO_IWRS_SV&_repFormat=csv&_dataSource=default&_outFilename=Subject_Visits.csv&_repLocale=en_US&_repEncoding=UTF-8&P_EDC_ROLE_ID=''+$v("P112_EDC_ROLE_ID_1")+''&P_EDC_USER=''+ $v("P'
||'112_EDC_USER_1") +''&P_EDC_USER_ID=''+ $v("P112_EDC_USER_ID_1")+'''',''_blank'');'
);
wwv_flow_imp.component_end;
end;
/
